"use client";
import {useMemo,useState} from 'react';
import {networkEdges,type RunPost} from '@/lib/crypto-run';
import styles from './crypto-research.module.css';
export function CryptoConnections({posts,onSelect}:{posts:RunPost[];onSelect:(id:string)=>void}){
 const [focus,setFocus]=useState('');
 const edges=useMemo(()=>networkEdges(posts),[posts]);
 const accounts=useMemo(()=>{const m=new Map<string,{id:string;handle:string;weight:number}>();for(const p of posts){if(!m.has(p.author_id))m.set(p.author_id,{id:p.author_id,handle:p.handle,weight:0});for(const e of p.edges)if(!m.has(e.target_id))m.set(e.target_id,{id:e.target_id,handle:e.target,weight:0});}for(const e of edges){m.get(e.source)!.weight+=e.weight;m.get(e.target)!.weight+=e.weight;}return [...m.values()].filter(a=>a.weight>0).sort((a,b)=>b.weight-a.weight||a.id.localeCompare(b.id));},[posts,edges]);
 const active=accounts.some(a=>a.id===focus)?focus:accounts[0]?.id;
 const nearby=edges.filter(e=>e.source===active||e.target===active);
 const neighbors=new Map<string,number>();for(const e of nearby){const id=e.source===active?e.target:e.source;neighbors.set(id,(neighbors.get(id)??0)+e.weight);}
 const allowed=new Set([...neighbors].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])).slice(0,8).map(([id])=>id));
 const shown=nearby.filter(e=>allowed.has(e.source===active?e.target:e.source));const ids=[active,...allowed].filter((id):id is string=>!!id);const graph={links:shown,nodes:ids.map((id,i)=>({id,x:i===0?430:430+280*Math.cos((i-1)*2*Math.PI/(ids.length-1)),y:i===0?235:235+165*Math.sin((i-1)*2*Math.PI/(ids.length-1))}))},positions=new Map(graph.nodes.map(n=>[n.id,n])),names=new Map(accounts.map(a=>[a.id,a.handle]));
 return <div><h3>Connections</h3><p className={styles.muted}>Choose an account to inspect its eight strongest observed connections.</p><label className={styles.connectionSelect}>Account<select aria-label="Connection account" value={active??''} onChange={e=>setFocus(e.target.value)}>{accounts.map(a=><option key={a.id} value={a.id}>@{a.handle} · {a.weight} interactions</option>)}</select></label>
 {!shown.length?<p className={styles.empty}>No saved connections in this period. This does not establish that no interactions occurred.</p>:<div className={styles.accountRows}>{shown.map(e=><article key={`${e.source}:${e.target}:${e.kind}`}><div><button className={styles.link} onClick={()=>onSelect(e.source)}>@{names.get(e.source)}</button><span> → </span><button className={styles.link} onClick={()=>onSelect(e.target)}>@{names.get(e.target)}</button></div><p className={styles.muted}>{e.weight} {e.kind} interaction{e.weight===1?'':'s'} · <a href={e.evidence} target="_blank" rel="noreferrer">View source ↗</a></p></article>)}</div>}
 {shown.length>0&&<details className={styles.methodology}><summary>Explore graph · selected account</summary><div className={styles.connectionGraph}><svg viewBox="0 0 860 470" role="img" aria-label="Selected account and up to eight strongest connected accounts" className="w-full">{graph.links.map(e=>{const a=positions.get(e.source)!,b=positions.get(e.target)!;return <line key={`${e.source}:${e.target}:${e.kind}`} x1={a.x} y1={a.y} x2={b.x} y2={b.y} stroke="#a78bfa" strokeOpacity=".5" strokeWidth="2"/>;})}{graph.nodes.map(n=><g key={n.id} role="button" tabIndex={0} aria-label={`Inspect ${names.get(n.id)}`} onClick={()=>onSelect(n.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect(n.id);}}}><circle cx={n.x} cy={n.y} r="26" fill={n.id===active?'#a78bfa':'#7dd3fc'}/><text x={n.x} y={n.y-34} textAnchor="middle" fill="var(--ink)" fontSize="16">{names.get(n.id)}</text></g>)}</svg></div><p className={styles.muted}>The list above supplies direction, interaction type and source evidence. Graph proximity does not establish coordination.</p></details>}
 <p className={styles.muted}>Quotes and replies can be critical. Interactions are not endorsements; liker identities are unavailable.</p></div>;
}
