"use client";
import {useEffect,useMemo,useState} from 'react';
import {filterEvidence,daysBetween,scopePosts,peopleIn,largestDailyGain,type RunData,type RunMarket} from '@/lib/crypto-run';
import type {Tracking} from '@/lib/crypto-social';
import {CryptoRunChart} from './crypto-run-chart';
import {CryptoPostBrowser} from './crypto-post-browser';
import {CryptoVoices} from './crypto-voices';
import {voiceEvidence} from '@/lib/crypto-voices';
import {CryptoWatchers} from './crypto-watchers';
import {CryptoConnections} from './crypto-connections';
import {CryptoLargeAccounts} from './crypto-large-accounts';
import {CryptoAccountDrawer} from './crypto-account-drawer';
import {CryptoPriceImpact} from './crypto-price-impact';
import {COINS,coinConfig} from '@/lib/crypto-coins';
import styles from './crypto-research.module.css';
type Meta={rolling?:{used_credits:number;credit_limit:number;end_at:string;last_saved:string|null;unfinished:number}|null;tracking?:Tracking|null;pilot?:{reserved_credits:number;credit_limit:number;outstanding:number};history?:{campaign:{reserved_credits:number;credit_limit:number}}|null};
export function CryptoSocialPanel(){
 const [allSearches,setAllSearches]=useState(false);
 const [evidenceMode,setEvidenceMode]=useState('words');
 const [coin,setCoin]=useState('ZCAT'),[tab,setTab]=useState('posts'),[pool,setPool]=useState('');
 const [run,setRun]=useState<RunData|null>(null),[market,setMarket]=useState<RunMarket|null>(null),[meta,setMeta]=useState<Meta|null>(null);
 const [error,setError]=useState(''),[marketLoading,setMarketLoading]=useState(true);
 const [from,setFrom]=useState('2026-07-25'),[to,setTo]=useState(new Date().toISOString().slice(0,10));
 const [selected,setSelected]=useState<string|null>(null);
 useEffect(()=>{const c=new AbortController();setRun(null);setMeta(null);setError('');setSelected(null);setFrom(coinConfig(coin).archiveStart);setTo(new Date().toISOString().slice(0,10));
  const load=async(path:string)=>{const r=await fetch(path,{signal:c.signal});const b=await r.json();if(!r.ok||!b.ok)throw new Error();return b.data;};
  load(`/api/market/crypto/run?coin=${coin}`).then(setRun).catch(()=>{if(!c.signal.aborted)setError('Saved research could not be loaded. Please reload to try again.');});
  load(`/api/market/crypto/social?coin=${coin}`).then(setMeta).catch(()=>{});return()=>c.abort();},[coin]);
 useEffect(()=>{const c=new AbortController();setMarketLoading(true);fetch(`/api/market/crypto/history?coin=${coin}${pool?'&pool='+encodeURIComponent(pool):''}`,{signal:c.signal})
  .then(async r=>{const b=await r.json();if(!r.ok||!b.ok)throw new Error();if(!c.signal.aborted){setMarket(b.data);setMarketLoading(false);}})
  .catch(()=>{if(!c.signal.aborted){setMarket(null);setMarketLoading(false);}});return()=>c.abort();},[coin,pool]);
 const days=useMemo(()=>daysBetween(run?.start??'2026-07-25',run?.end??new Date().toISOString().slice(0,10)),[run?.start,run?.end]);
 const eligible=useMemo(()=>evidenceMode==='words'?voiceEvidence(run?.posts??[],coin).eligible:filterEvidence(run?.posts??[],coin,evidenceMode),[run,coin,evidenceMode]);
 const posts=useMemo(()=>scopePosts(eligible,from,to),[eligible,from,to]);const people=useMemo(()=>peopleIn(posts),[posts]);
 const authors=people.filter(p=>p.posts.length>0).sort((a,b)=>a.posts[0].posted_at.localeCompare(b.posts[0].posted_at)||a.id.localeCompare(b.id));
 const series=marketLoading?[]:market?.points??[],gain=largestDailyGain(series.filter(p=>p.day>=from&&p.day<=to));
 const person=people.find(p=>p.id===selected);
 const searchedDays=(run?.days??[]).filter(d=>d.day>=from&&d.day<=to&&d.searched>0).length,first=authors[0]?.posts[0];
 const range=(a:string,b:string)=>{setFrom(a);setTo(b);setSelected(null);};
 return <section className={`${styles.panel} ${styles.explorer}`} aria-label="Crypto run explorer">
  <header className={styles.explorerHeader}><div><p className={styles.label}>Research workspace</p><h2>Crypto intelligence</h2><p className={styles.muted}>Find the accounts. Understand the timing. Follow the evidence.</p></div><select hidden={tab==='watchers'} aria-label="Research coin" value={allSearches?'ALL':coin} onChange={e=>{setPool('');setEvidenceMode('words');setAllSearches(e.target.value==='ALL');if(e.target.value==='ALL')setTab(previous=>previous==='watchers'?'watchers':'posts');else setCoin(e.target.value);}}>{COINS.map(c=><option key={c.symbol} value={c.symbol}>{c.label}</option>)}<option value="ALL">All tracked coins</option></select></header>
  <nav className={styles.viewTabs} aria-label="Research views">{[['posts','Posts'],['reach','Accounts'],['run','Insights'],['watchers','Watchers']].map(([id,label])=><button key={id} aria-pressed={id==='posts'?tab==='posts':id==='reach'?['reach','voices','impact'].includes(tab):id==='watchers'?tab==='watchers':['run','network','sentiment'].includes(tab)} onClick={()=>{setTab(id);if(id!=='posts')setAllSearches(id==='watchers');}}>{label}</button>)}</nav>
  {['reach','voices','impact'].includes(tab)&&<div className={styles.secondaryTabs} aria-label="Account view"><button aria-pressed={tab==='reach'} onClick={()=>{setTab('reach');setAllSearches(false);}}>Largest audiences</button><button aria-pressed={tab==='voices'} onClick={()=>{setTab('voices');setAllSearches(false);}}>Voice roles</button><button aria-pressed={tab==='impact'} onClick={()=>{setTab('impact');setAllSearches(false);}}>Price after posting</button></div>}
  {['run','network','sentiment'].includes(tab)&&<div className={styles.secondaryTabs} aria-label="Insight view"><button aria-pressed={tab==='run'} onClick={()=>setTab('run')}>Price & timing</button><button aria-pressed={tab==='sentiment'} onClick={()=>setTab('sentiment')}>Sentiment</button><button aria-pressed={tab==='network'} onClick={()=>setTab('network')}>Connections</button></div>}

  {!['posts','sentiment','watchers','voices','impact'].includes(tab)&&<details className={styles.scopeControls}><summary><span>Dates & evidence</span><span className={styles.scopeSummary}>{from} → {to} · {evidenceMode==='contract'?'Exact contract':evidenceMode==='all'?'All results':'Coin mentions'}</span></summary><div className={styles.rangeBar}><div className="flex flex-wrap items-end gap-2"><label>From (UTC)<input type="date" aria-label="Selection start" value={from} min={days[0]} max={to} onInput={e=>{const value=e.currentTarget.value;if(value>=days[0]&&value<=to)range(value,to);}} onChange={e=>{if(e.target.value>=days[0]&&e.target.value<=to)range(e.target.value,to);}}/></label><span className="pb-3">→</span><label>Through (UTC)<input type="date" aria-label="Selection end" value={to} min={from} max={days.at(-1)} onInput={e=>{const value=e.currentTarget.value;if(value>=from&&value<=days[days.length-1])range(from,value);}} onChange={e=>{if(e.target.value>=from&&e.target.value<=days[days.length-1])range(from,e.target.value);}}/></label><button className={styles.control} onClick={()=>range(days[0],days[days.length-1])}>Full period</button></div><p className={styles.muted}>{posts.length.toLocaleString()} saved posts · {authors.length} authors in selection</p></div>
  <div className={styles.toolbar}><label className={styles.muted}>Evidence filter <select aria-label="Evidence filter" value={evidenceMode} onChange={e=>{setEvidenceMode(e.target.value);setSelected(null);}}><option value="words">Coin words in post</option>{coin!=='ZEC'&&<option value="contract">Exact contract in post</option>}<option value="all">All saved search results</option></select></label><p className={styles.muted}>{eligible.length} / {run?.posts.length??0} loaded posts match · text matching does not verify endorsement</p></div></details>}
  {tab!=='watchers'&&coin==='DPONS'&&<p className={`${styles.coverageNote} break-words`}>Diamond Pons · Robinhood Chain · Contract 0x0e6d1ebb33f3b8f2d09bacf3b1a1d5c581110c33. Historical collection is authorized up to 150,000 credits in a separate DPONS campaign. Saved coverage and reservations appear under Data sources & collection status.</p>}
  {tab==='watchers'?<CryptoWatchers coin="ALL"/>:error?<p className={styles.empty} role="alert">{error}</p>:!run?<p className={styles.empty}>Loading the saved timeline…</p>:<>
   {run.total>run.limit&&<p className={styles.coverageNote}>Showing the earliest {run.limit.toLocaleString()} of {run.total.toLocaleString()} saved posts. Social charts and rankings use this limited set.</p>}
   {coin==='STANDARD'&&<p className={`${styles.muted} break-words`}>Robinhood Chain · Contract 0x88ad8ddf1e3898412146a534538d418c6f8a9062. Matches use the contract, cashtag and project names; ordinary uses of “standard” are excluded.</p>}
   {tab==='run'&&<>
    <div className={styles.toolbar}><p className={styles.muted}>Looking for accounts with a large audience?</p><button className={styles.control} onClick={()=>setTab('reach')}>Explore large accounts →</button></div><div className={styles.takeaways}><button disabled={!first} onClick={()=>{if(first)setSelected(first.author_id);}}><span>Earliest author found</span><strong>{first?'@'+first.handle:'No posts in selection'}</strong><small>{first?first.posted_at.slice(0,10)+' · open evidence':'Collection is still building the picture.'}</small></button><button disabled={!gain} onClick={()=>{if(gain)range(gain.day,gain.day);}}><span>Largest daily price gain</span><strong className={styles.positive}>{gain?'+'+gain.percent.toLocaleString(undefined,{maximumFractionDigits:1})+'%':'Awaiting comparable prices'}</strong><small>{gain?gain.day+' · inspect this day':'Requires observations on consecutive days.'}</small></button><div><span>Search coverage</span><strong>{searchedDays} / {daysBetween(from,to).length} days sampled</strong><small>Unequal coverage limits comparisons.</small></div></div>
    <div className={styles.chartCard}><div className={styles.toolbar}><h3>Price & attention</h3><div className={styles.legend}><span style={{color:'#7dd3fc'}}>● Market</span><span style={{color:'#c4b5fd'}}>● Social</span><span style={{color:'#fbbf24'}}>● Missing coverage</span></div></div>
     {marketLoading&&<p className={styles.muted}>Loading historical market data…</p>}
     <CryptoRunChart days={days} market={series} posts={eligible} coverage={run.days??[]} from={from} to={to} onRange={range}/>
     <div className={styles.marketSource}>{!marketLoading&&market?.selected&&<label>Market source<select aria-label="Trading pool" value={market.selected.id} onChange={e=>setPool(e.target.value)}>{market.pools.map(p=><option key={p.id} value={p.id}>{p.name} · {p.created.slice(0,10)} · {p.id.slice(0,6)}</option>)}</select></label>}<div><a className={styles.link} href={market?.sourceUrl??'https://www.geckoterminal.com/'} target="_blank" rel="noreferrer">{market?.source??'Market source'} ↗</a><p className={styles.muted}>{market?.note??'Market history is unavailable; saved social evidence remains accessible.'}</p>{market?.observedAt&&<p className={styles.muted}>Saved {new Date(market.observedAt).toLocaleString()} · {market.archiveRevisions??0} archived fetches{Date.now()-Date.parse(market.observedAt)>12*3600000?' · Update overdue; showing saved history':''}</p>}</div></div>
     {!marketLoading&&market?.selected&&<p className={styles.coverageNote}>Selected pool created {market.selected.created.slice(0,10)}. Earlier dates have no price history from this pool. This is not a verified token launch date.</p>}
    </div>
    {coin!=='ZEC'&&<p className={styles.coverageNote}>Early name and ticker matches may refer to a different token. Check the contract in source posts before treating them as launch evidence.</p>}<div className={styles.toolbar}><h3>Evidence in this period</h3><button className={styles.control} onClick={()=>setTab('voices')}>Explore early voices →</button></div>
    {posts.length?<div className={styles.eventList}>{posts.slice(0,8).map(p=><article key={p.id}><time>{p.posted_at.slice(0,16).replace('T',' ')} UTC</time><div className="flex justify-between gap-3"><button className={styles.link} onClick={()=>setSelected(p.author_id)}>@{p.handle}</button><a className={styles.muted} href={p.url} target="_blank" rel="noreferrer">Source ↗</a></div><p className={styles.postExcerpt}>{p.text}</p><span className={styles.badge}>{p.kind}</span></article>)}</div>:<p className={styles.empty}>No saved posts in this period. Unsampled periods do not establish that nobody was discussing the coin.</p>}
    {posts.length>8&&<p className={`${styles.muted} mt-3`}>Earliest eight posts in the selection. <button className={styles.link} onClick={()=>setTab('posts')}>Search all saved posts →</button></p>}
   </>}
   <div hidden={!['posts','sentiment'].includes(tab)}><CryptoPostBrowser key={coin} coin={coin} run={run} allSearches={allSearches} insightsOnly={tab==='sentiment'} onBrowse={()=>setTab('posts')}/></div>
   {tab==='reach'&&<CryptoLargeAccounts key={coin} posts={posts} suggestedDay={gain?.day??''} onSelect={setSelected}/>}
   {tab==='voices'&&<CryptoVoices coin={coin}/>}
   {tab==='impact'&&<CryptoPriceImpact coin={coin} onSelect={setSelected}/>}
   {tab==='network'&&<CryptoConnections posts={posts} onSelect={setSelected}/>}
  </>}
  {tab!=='watchers'&&coin==='PONS'&&<p className={styles.coverageNote}>PONS · Robinhood Chain · Contract 0x39dbed3a2bd333467115de45665cc57f813c4571. Profiles captured with posts provide a current baseline; historical follower growth cannot be reconstructed from current counts.</p>}<details hidden={tab==='watchers'} className={styles.methodology}><summary>Data sources & collection status</summary>{meta?.rolling&&<p className={styles.coverageNote}>Rolling collection: every 6 hours · daily follower/bio snapshots for up to 20 accounts. {meta.rolling.used_credits.toLocaleString()} / {meta.rolling.credit_limit.toLocaleString()} credits charged or reserved for {coin}. Ends {meta.rolling.end_at.slice(0,10)}. Last saved request: {meta.rolling.last_saved??'None yet'}. {meta.rolling.unfinished} windows still need pagination; counts are incomplete until searched.</p>}<p className={styles.muted}>Social evidence comes from saved records. Market observations and their original responses are archived in Postgres from public APIs. Viewing and filtering spend no TwitterAPI.io credits. Search results are incomplete; temporal alignment does not establish causation.</p>{market?.investigation&&<p className={styles.coverageNote}>Historical collection: {market.investigation.focus_reason} Each batch allows up to {market.investigation.max_requests} requests. Unsearched windows come first, with priority on the buildup period; additional pages follow in rounds within the existing credit ceiling.</p>}{meta?.pilot&&<p className={styles.muted}>Live pilot: {meta.pilot.reserved_credits.toLocaleString()} / {meta.pilot.credit_limit.toLocaleString()} credits reserved. {meta.pilot.outstanding>0?'Collection is paused for an outstanding or uncertain request.':''}</p>}{meta?.history&&<p className={styles.muted}>History: {meta.history.campaign.reserved_credits.toLocaleString()} / {meta.history.campaign.credit_limit.toLocaleString()} reserved.</p>}{coin==='ZCAT'&&<p className={`${styles.muted} break-words`}>Contract HcRLc9VDgjLeK154xDawfb1dmVJ98DoSqcwTHGqiDeJR is matched against pool token relationships and <a className="underline" href="https://bigone.zendesk.com/hc/en-us/articles/62063867754777-BigONE-Alpha-Lists-ZCAT-Anonymous-Cat" target="_blank" rel="noreferrer">BigONE’s September 9 listing announcement</a>. Default pool: pinned when first archived, initially the oldest among the five most liquid returned pools. Historical liquidity is not in these candles; pool prices and volume are not token-wide aggregates.</p>}</details>
  {person&&<CryptoAccountDrawer key={person.id} person={person} tracking={meta?.tracking??null} onClose={()=>setSelected(null)}/>}
 </section>;
}
