"use client";
import {useState} from 'react';
import type {RunPost} from '@/lib/crypto-run';
import {sentimentDays,sentimentLabels,type Sentiment} from '@/lib/crypto-intelligence';
import styles from './crypto-research.module.css';
export function CryptoSentimentView({posts,annotations,coin,onDay}:{posts:RunPost[];annotations:Sentiment[];coin:string;onDay:(day:string,label:string)=>void}){
 const [balanced,setBalanced]=useState(false);
 const days=sentimentDays(posts,annotations,coin,balanced),ids=new Set(posts.map(p=>p.id)),classified=annotations.filter(a=>a.coin===coin&&ids.has(a.post_id)&&!a.excluded).length,excluded=annotations.filter(a=>a.coin===coin&&ids.has(a.post_id)&&a.excluded).length;
 return <details className={styles.scopeControls}><summary><span>Daily sentiment · {coin}</span><span className={styles.scopeSummary}>{classified} / {ids.size-excluded} eligible posts classified · evaluation sample</span></summary>
 <p className={styles.coverageNote}>Provisional assistant/model labels; not independently human-validated. {excluded>0?`${excluded} unrelated/context-missing records excluded from this chart.`:''} Percentages describe classified samples, not all X discussion. Sparse samples and missing search coverage can create misleading swings. Unclassified posts are separate from neutral.</p>
 <label className={styles.checkLabel}><input type="checkbox" checked={balanced} onChange={e=>setBalanced(e.target.checked)}/> One contribution per author per day</label><p className={styles.muted}>{balanced?'Each author’s classified stances are combined; conflicting labels become mixed. Unclassified posts from partially classified authors do not establish their stance.':'Each classified post contributes equally.'} Click a colored segment to inspect that day’s posts. In author-balanced mode, clicking opens all posts for the day because mixed author stances may span multiple posts. Percentages below use classified {balanced?'authors':'posts'} only.</p>
 <div className={styles.sentimentLegend}>{[...sentimentLabels,'unclassified'].map(label=><span key={label} className={styles[label]}>{label}</span>)}</div>
 <div className={styles.sentimentTimeline}>{days.map((d,i)=>{const previous=days[i-1],delta=d.bullish!=null&&previous?.bullish!=null&&Date.parse(d.day)-Date.parse(previous.day)===86400000?d.bullish-previous.bullish:null;return <div className={styles.sentimentDay} key={d.day}><button className={styles.link} onClick={()=>onDay(d.day,'all')}>{d.day}</button><div className={styles.sentimentBar}>{[...sentimentLabels,'unclassified'].filter(l=>d.counts[l]>0).map(l=><button key={l} className={styles[l]} style={{flexGrow:d.counts[l]}} title={`${l}: ${d.counts[l]}`} aria-label={`${d.day} ${l}: ${d.counts[l]}`} onClick={()=>onDay(d.day,balanced?'all':l)}/>)}</div><span className={styles.muted}>{d.classified}/{d.total} classified · {d.bullish==null?'—':d.bullish.toFixed(0)+'% bullish'} · {d.bearish==null?'—':d.bearish.toFixed(0)+'% bearish'}{delta!=null?` · ${delta>=0?'+':''}${delta.toFixed(0)} pp bullish`:''}{d.classified<20?' · Small sample':''}</span></div>;})}</div>
 {!classified&&<p className={styles.empty}>No classified posts in this view yet. The pilot must finish before sentiment results appear.</p>}
 </details>;
}
