"use client";
import {useEffect,useState} from 'react';
import {watcherSignals} from '@/lib/crypto-watchers';
import styles from './crypto-research.module.css';
type Post={id:string;author_id:string;handle:string;text:string;posted_at:string;kind:string;url:string};
type Data={posts:Post[];hasMore:boolean;accounts:{id:string;handle:string}[];campaign:null|{used_credits:number;credit_limit:number;end_at:string;last_saved:string|null;outstanding_request:boolean};coverage:{account_id:string;unfinished:number;searched_through:string|null}[]};
export function CryptoWatcherFeed(){
 const [data,setData]=useState<Data|null>(null),[account,setAccount]=useState(''),[offset,setOffset]=useState(0),[retry,setRetry]=useState(0),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 useEffect(()=>{const c=new AbortController();setLoading(true);setError('');fetch(`/api/market/crypto/watcher-feed?account=${account}&offset=${offset}`,{signal:c.signal}).then(async r=>{const b=await r.json();if(!r.ok||!b.ok)throw Error();setData(b.data);}).catch(()=>{if(!c.signal.aborted)setError('Could not load watcher posts.');}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[account,offset,retry]);
 const campaign=data?.campaign,unfinished=data?.coverage.filter(c=>!account||c.account_id===account).reduce((n,c)=>n+c.unfinished,0)??0;
 return <section aria-label="Tracked watcher posts"><h3>Latest watcher posts</h3><p className={styles.muted}>10 reviewed accounts · all assets · scheduled every 2 hours. Viewing saved posts uses no X credits.</p>
 {campaign&&<p className={styles.coverageNote}>{campaign.used_credits+300>campaign.credit_limit||Date.now()>=Date.parse(campaign.end_at)?'Collection allowance ended':campaign.outstanding_request?'Collection in progress or awaiting ledger review':'Two-hour collection enabled'} · {campaign.used_credits.toLocaleString()} / {campaign.credit_limit.toLocaleString()} estimated credits, including reservations. Ends {campaign.end_at.slice(0,10)}.<br/>Last saved search: {campaign.last_saved?new Date(campaign.last_saved).toLocaleString():'not yet'}. {unfinished>0?`${unfinished} unfinished search windows; coverage is incomplete.`:'No unfinished windows recorded.'}</p>}
 <label>Account <select className={styles.control} value={account} onChange={e=>{setAccount(e.target.value);setOffset(0);}}><option value="">All 10 watchers</option>{data?.accounts.map(a=><option key={a.id} value={a.id}>@{a.handle}</option>)}</select></label> <button className={styles.control} onClick={()=>setRetry(n=>n+1)}>Refresh saved posts</button>
 {error?<p role="alert">{error} <button onClick={()=>setRetry(n=>n+1)}>Retry</button></p>:loading?<p role="status">Loading watcher posts…</p>:<><p className={styles.muted}>Whale and volume labels describe the post’s wording. Claims have not been verified against blockchain data.</p><div className={styles.accountRows}>{data?.posts.map(p=>{const s=watcherSignals(p.text);return <article key={p.id}><div className={styles.mobileAccountHeader}><a className={styles.link} href={`https://x.com/i/user/${p.author_id}`} target="_blank" rel="noreferrer">@{p.handle}</a><span className={styles.muted}>{new Date(p.posted_at).toLocaleString()}</span></div><p className={styles.muted}>{s.supported?(s.whale&&s.volume?'Whale & volume':s.whale?'Whale activity':'Trading volume'):'Other post'} · {p.kind}</p>{p.text.length>600?<details><summary>{p.text.slice(0,180)}… Read full post</summary><p className={styles.postFullText}>{p.text}</p></details>:<p className={styles.postFullText}>{p.text}</p>}<a className={styles.link} href={p.url} target="_blank" rel="noreferrer">Open on X ↗</a></article>;})}</div>{!data?.posts.length&&<p className={styles.empty}>{campaign?'No saved watcher posts on this page. Try another account or refresh after collection.':'The first watcher collection has not completed yet.'}</p>}<div className={styles.secondaryTabs}><button disabled={offset===0} onClick={()=>setOffset(n=>Math.max(0,n-25))}>Previous</button><span>Page {offset/25+1}</span><button disabled={!data?.hasMore} onClick={()=>setOffset(n=>n+25)}>Next 25</button></div></>}
 <details className={styles.methodology}><summary>Tracked accounts & collection coverage</summary><p className={styles.muted}>This fixed list comes from our reviewed top 10. Account rankings can change without changing who is collected. Each run searches recent posts with a one-hour overlap, up to two pages per account. The first run starts with the preceding 24 hours. Duplicate posts are stored once. Each run prioritizes a fresh window, then resumes the oldest unfinished window; this is search coverage, not a guaranteed complete account archive. Scheduled runs can be delayed.</p>{data?.accounts.map(a=>{const c=data.coverage.find(c=>c.account_id===a.id);return <p key={a.id}>@{a.handle} · {c?`${c.unfinished} unfinished windows`:'Awaiting first search'}</p>;})}</details>
 </section>;
}
