"use client";
import {useEffect,useState} from 'react';
import styles from './crypto-research.module.css';
type Status={status:string;coverage:{symbol:string;days_total:number;days_searched:number;unfinished:number;first_window:string|null;searched_through:string|null;origin:{pages:number;status:string;start_at:string|null;end_at:string|null}|null;hourly_hours:number;hourly_latest:string|null;source_id:string|null}[];ledgers:{name:string;used:number;ceiling:number;ends:string|null}[];registry:{symbol:string;name:string;network:string;address:string|null;archiveStart:string;originFrom:string|null;official:string[];matches:string[]}[];watchers:{id:string;handle:string}[];lastCollection:string|null;outstanding?:number};
export function CryptoDataView({onCoin}:{onCoin:(coin:string)=>void}){
 const [data,setData]=useState<Status|null>(null),[error,setError]=useState('');
 useEffect(()=>{const c=new AbortController();fetch('/api/market/crypto/status',{signal:c.signal}).then(async r=>{const b=await r.json();if(!r.ok||!b.ok)throw Error();setData(b.data);}).catch(()=>{if(!c.signal.aborted)setError('Status could not be loaded.');});return()=>c.abort();},[]);
 return <div style={{display:'flex',flexDirection:'column',gap:18}}>
  <div className={styles.wsTitle}><h2>Can I trust the data today?</h2><p>Coverage per coin, credit ledgers and the registry. Other pages link here whenever coverage limits a comparison.</p></div>
  {error?<p role="alert" className={styles.empty}>{error}</p>:!data?<p role="status" className={styles.muted}>Loading status…</p>:<>
  <div className={styles.wsGrid}>
   <section className={styles.wsSection}><h3>Coverage per coin</h3><div className={styles.table}><table><thead><tr><th>Coin</th><th>Days searched</th><th>Origin search</th><th>Hourly prices</th><th>Gaps</th></tr></thead><tbody>{data.coverage.map(c=><tr key={c.symbol}><td><button className={styles.link} onClick={()=>onCoin(c.symbol)}><strong>{c.symbol}</strong></button></td><td className={c.days_searched<c.days_total?styles.negative:''}>{c.days_searched} / {c.days_total}<small className={styles.cellNote}>{c.searched_through?'through '+String(c.searched_through).slice(0,10):'nothing searched yet'}</small></td><td>{!c.origin?<small>n/a</small>:c.origin.status==='search_exhausted'?'complete':c.origin.status==='pending'&&c.origin.pages===0?'queued':`${c.origin.pages} page${c.origin.pages===1?'':'s'} so far`}<small className={styles.cellNote}>{c.origin?.start_at?'from '+String(c.origin.start_at).slice(0,10):''}</small></td><td>{c.hourly_hours?`${c.hourly_hours.toLocaleString()} h`:<small>none yet</small>}<small className={styles.cellNote}>{c.hourly_latest?'latest '+String(c.hourly_latest).slice(0,13).replace('T',' ')+'h':c.source_id?'':'no indexed pool'}</small></td><td><small>{c.unfinished?`${c.unfinished} windows unfinished`:'—'}</small></td></tr>)}</tbody></table></div><small className={styles.muted}>Unsearched days never mean silence. Origin = one contract-only search back to the registry date for coins added after launch.</small></section>
   <section className={styles.wsSection}><h3>Credits · TwitterAPI.io, 100,000 per USD</h3><div className={styles.table}><table><thead><tr><th>Campaign</th><th>Used</th><th>Ceiling</th><th></th><th>Ends</th></tr></thead><tbody>{data.ledgers.map(l=>{const p=l.ceiling?Math.min(100,Math.round(l.used/l.ceiling*100)):0;return <tr key={l.name}><td>{l.name}</td><td>{l.used.toLocaleString()}</td><td>{l.ceiling.toLocaleString()}</td><td><div className={styles.wsBar}><div className={p>70?'warn':''} style={{width:p+'%'}}></div></div></td><td><small>{l.ends?String(l.ends).slice(0,10):'fixed'}</small></td></tr>;})}</tbody></table></div><small className={styles.muted}>Ceilings are ours; the provider balance is not visible here. Last saved request {data.lastCollection?String(data.lastCollection).slice(0,16).replace('T',' ')+' UTC':'none'}{data.outstanding?` · ${data.outstanding} request awaiting ledger review`:' · no outstanding requests'}.</small></section>
  </div>
  <section className={styles.wsSection}><h3>Registry · {data.registry.length} coins</h3><div className={styles.table}><table><thead><tr><th>Coin</th><th>Contract</th><th>Matches on</th><th>Official handles</th><th>Since</th></tr></thead><tbody>{data.registry.map(r=><tr key={r.symbol}><td><strong>{r.symbol}</strong><small className={styles.cellNote}>{r.name} · {r.network}</small></td><td><span className={styles.wsMono} style={{overflowWrap:'anywhere'}}>{r.address??'native'}</span></td><td><small>{r.matches.join(' · ')}</small></td><td><small>{r.official.length?r.official.map(h=>'@'+h).join(', '):'none configured'}</small></td><td><small>{r.archiveStart}{r.originFrom?' · origin '+r.originFrom:''}</small></td></tr>)}</tbody></table></div><small className={styles.muted}>Adding a coin is one registry entry (apps/web/lib/crypto-coins.json). Official handles mark interested sources so they never rank as independent voices. Watched accounts: {data.watchers.map(w=>'@'+w.handle).join(', ')} plus every account with a track record.</small></section>
  </>}
 </div>;
}
