"use client";
import {useEffect,useMemo,useState} from 'react';
import {filterEvidence,daysBetween,scopePosts,peopleIn,networkEdges,layoutNetwork,largestDailyGain,type RunData,type RunMarket} from '@/lib/crypto-run';
import type {Tracking} from '@/lib/crypto-social';
import {CryptoInfluencerPanel} from './crypto-influencer-panel';
import {CryptoRunChart} from './crypto-run-chart';
import {CryptoAccountDrawer} from './crypto-account-drawer';
import styles from './crypto-research.module.css';
type Meta={tracking?:Tracking|null;pilot?:{reserved_credits:number;credit_limit:number;outstanding:number};history?:{campaign:{reserved_credits:number;credit_limit:number}}|null};
export function CryptoSocialPanel(){
 const [evidenceMode,setEvidenceMode]=useState('words');
 const [coin,setCoin]=useState('ZCAT'),[tab,setTab]=useState('run'),[pool,setPool]=useState('');
 const [run,setRun]=useState<RunData|null>(null),[market,setMarket]=useState<RunMarket|null>(null),[meta,setMeta]=useState<Meta|null>(null);
 const [error,setError]=useState(''),[marketLoading,setMarketLoading]=useState(true);
 const [from,setFrom]=useState('2026-07-25'),[to,setTo]=useState(new Date().toISOString().slice(0,10));
 const [selected,setSelected]=useState<string|null>(null),[kind,setKind]=useState('all'),[search,setSearch]=useState(''),[edgeSelection,setEdgeSelection]=useState<string|null>(null);
 useEffect(()=>{const c=new AbortController();setRun(null);setMeta(null);setError('');setSelected(null);setFrom('2026-07-25');setTo(new Date().toISOString().slice(0,10));
  const load=async(path:string)=>{const r=await fetch(path,{signal:c.signal});const b=await r.json();if(!r.ok||!b.ok)throw new Error();return b.data;};
  load(`/api/market/crypto/run?coin=${coin}`).then(setRun).catch(()=>{if(!c.signal.aborted)setError('Saved research could not be loaded. Please reload to try again.');});
  load(`/api/market/crypto/social?coin=${coin}`).then(setMeta).catch(()=>{});return()=>c.abort();},[coin]);
 useEffect(()=>{const c=new AbortController();setMarketLoading(true);fetch(`/api/market/crypto/history?coin=${coin}${pool?'&pool='+encodeURIComponent(pool):''}`,{signal:c.signal})
  .then(async r=>{const b=await r.json();if(!r.ok||!b.ok)throw new Error();if(!c.signal.aborted){setMarket(b.data);setMarketLoading(false);}})
  .catch(()=>{if(!c.signal.aborted){setMarket(null);setMarketLoading(false);}});return()=>c.abort();},[coin,pool]);
 const days=useMemo(()=>daysBetween(run?.start??'2026-07-25',run?.end??new Date().toISOString().slice(0,10)),[run?.start,run?.end]);
 const eligible=useMemo(()=>filterEvidence(run?.posts??[],coin,evidenceMode),[run,coin,evidenceMode]);
 const posts=useMemo(()=>scopePosts(eligible,from,to),[eligible,from,to]);const people=useMemo(()=>peopleIn(posts),[posts]);
 const authors=people.filter(p=>p.posts.length>0).sort((a,b)=>a.posts[0].posted_at.localeCompare(b.posts[0].posted_at)||a.id.localeCompare(b.id));
 const series=marketLoading?[]:market?.points??[],gain=largestDailyGain(series.filter(p=>p.day>=from&&p.day<=to));
 const edges=useMemo(()=>networkEdges(posts,kind),[posts,kind]),graph=useMemo(()=>layoutNetwork(edges),[edges]);
 const positions=new Map(graph.nodes.map(n=>[n.id,n])),names=new Map(people.map(p=>[p.id,p.handle]));const person=people.find(p=>p.id===selected);
 const searchedDays=(run?.days??[]).filter(d=>d.day>=from&&d.day<=to&&d.searched>0).length,first=authors[0]?.posts[0];
 const range=(a:string,b:string)=>{setFrom(a);setTo(b);setSelected(null);setEdgeSelection(null);};
 const chosenEdge=graph.links.find(e=>`${e.source}:${e.target}:${e.kind}`===edgeSelection);
 return <section className={`${styles.panel} ${styles.explorer}`} aria-label="Crypto run explorer">
  <header className={styles.explorerHeader}><div><p className={styles.label}>Community intelligence</p><h2>How the run unfolded</h2><p className={styles.muted}>Follow the price. Find the early voices. Inspect the evidence.</p></div><select aria-label="Research coin" value={coin} onChange={e=>{setPool('');setEvidenceMode('words');setCoin(e.target.value);}}><option value="ZCAT">ZCAT · Anonymous Cat</option><option value="ZEC">ZEC · Zcash</option></select></header>
  <nav className={styles.viewTabs} aria-label="Research views">{[['run','The Run'],['voices','Early Voices'],['network','The Network']].map(([id,label])=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}>{label}</button>)}</nav>
  <div className={styles.rangeBar}><div className="flex flex-wrap items-end gap-2"><label>From (UTC)<input type="date" aria-label="Selection start" value={from} min={days[0]} max={to} onInput={e=>{const value=e.currentTarget.value;if(value>=days[0]&&value<=to)range(value,to);}} onChange={e=>{if(e.target.value>=days[0]&&e.target.value<=to)range(e.target.value,to);}}/></label><span className="pb-3">→</span><label>Through (UTC)<input type="date" aria-label="Selection end" value={to} min={from} max={days.at(-1)} onInput={e=>{const value=e.currentTarget.value;if(value>=from&&value<=days[days.length-1])range(from,value);}} onChange={e=>{if(e.target.value>=from&&e.target.value<=days[days.length-1])range(from,e.target.value);}}/></label><button className={styles.control} onClick={()=>range(days[0],days[days.length-1])}>Full period</button></div><p className={styles.muted}>{posts.length.toLocaleString()} saved posts · {authors.length} authors in selection</p></div>
  <div className={styles.toolbar}><label className={styles.muted}>Evidence filter <select aria-label="Evidence filter" value={evidenceMode} onChange={e=>{setEvidenceMode(e.target.value);setSelected(null);setEdgeSelection(null);}}><option value="words">Coin words in post</option>{coin==='ZCAT'&&<option value="contract">Exact contract in post</option>}<option value="all">All saved search results</option></select></label><p className={styles.muted}>{eligible.length} / {run?.posts.length??0} loaded posts match · text matching does not verify endorsement</p></div>
  {error?<p className={styles.empty} role="alert">{error}</p>:!run?<p className={styles.empty}>Loading the saved timeline…</p>:<>
   {run.total>run.limit&&<p className={styles.coverageNote}>Showing the earliest {run.limit.toLocaleString()} of {run.total.toLocaleString()} saved posts. Social charts and rankings use this limited set.</p>}
   {tab==='run'&&<>
    <div className={styles.takeaways}><button disabled={!first} onClick={()=>{if(first)setSelected(first.author_id);}}><span>Earliest author found</span><strong>{first?'@'+first.handle:'No posts in selection'}</strong><small>{first?first.posted_at.slice(0,10)+' · open evidence':'Collection is still building the picture.'}</small></button><button disabled={!gain} onClick={()=>{if(gain)range(gain.day,gain.day);}}><span>Largest daily price gain</span><strong className={styles.positive}>{gain?'+'+gain.percent.toLocaleString(undefined,{maximumFractionDigits:1})+'%':'Awaiting comparable prices'}</strong><small>{gain?gain.day+' · inspect this day':'Requires observations on consecutive days.'}</small></button><div><span>Search coverage</span><strong>{searchedDays} / {daysBetween(from,to).length} days sampled</strong><small>Unequal coverage limits comparisons.</small></div></div>
    <div className={styles.chartCard}><div className={styles.toolbar}><h3>Price & attention</h3><div className={styles.legend}><span style={{color:'#7dd3fc'}}>● Market</span><span style={{color:'#c4b5fd'}}>● Social</span><span style={{color:'#fbbf24'}}>● Missing coverage</span></div></div>
     {marketLoading&&<p className={styles.muted}>Loading historical market data…</p>}
     <CryptoRunChart days={days} market={series} posts={eligible} coverage={run.days??[]} from={from} to={to} onRange={range}/>
     <div className={styles.marketSource}>{!marketLoading&&market?.selected&&<label>Market source<select aria-label="Trading pool" value={market.selected.id} onChange={e=>setPool(e.target.value)}>{market.pools.map(p=><option key={p.id} value={p.id}>{p.name} · {p.created.slice(0,10)} · {p.id.slice(0,6)}</option>)}</select></label>}<div><a className={styles.link} href={market?.sourceUrl??'https://www.geckoterminal.com/'} target="_blank" rel="noreferrer">{market?.source??'Market source'} ↗</a><p className={styles.muted}>{market?.note??'Market history is unavailable; saved social evidence remains accessible.'}</p>{market?.observedAt&&<p className={styles.muted}>Saved {new Date(market.observedAt).toLocaleString()} · {market.archiveRevisions??0} archived fetches{Date.now()-Date.parse(market.observedAt)>12*3600000?' · Update overdue; showing saved history':''}</p>}</div></div>
     {!marketLoading&&market?.selected&&<p className={styles.coverageNote}>Selected pool created {market.selected.created.slice(0,10)}. Earlier dates have no price history from this pool. This is not a verified token launch date.</p>}
    </div>
    {coin==='ZCAT'&&<p className={styles.coverageNote}>Early name and ticker matches may refer to a different token. Check the contract in source posts before treating them as launch evidence.</p>}<div className={styles.toolbar}><h3>Evidence in this period</h3><button className={styles.control} onClick={()=>setTab('voices')}>Explore early voices →</button></div>
    {posts.length?<div className={styles.eventList}>{posts.slice(0,8).map(p=><article key={p.id}><time>{p.posted_at.slice(0,16).replace('T',' ')} UTC</time><div className="flex justify-between gap-3"><button className={styles.link} onClick={()=>setSelected(p.author_id)}>@{p.handle}</button><a className={styles.muted} href={p.url} target="_blank" rel="noreferrer">Source ↗</a></div><p className={styles.postExcerpt}>{p.text}</p><span className={styles.badge}>{p.kind}</span></article>)}</div>:<p className={styles.empty}>No saved posts in this period. Unsampled periods do not establish that nobody was discussing the coin.</p>}
    {posts.length>8&&<p className={`${styles.muted} mt-3`}>Earliest eight posts in the selection. Open an account for more evidence.</p>}
   </>}
   {tab==='voices'&&<><div className={styles.toolbar}><div><h3>Who appeared early?</h3><p className={styles.muted}>Ordered by first saved post within your selected dates.</p></div><input type="search" aria-label="Search early voices" placeholder="Find an account…" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className={styles.table}><table><thead><tr><th className="text-left">Account</th><th>First saved post</th><th>Posts</th><th>People interacting</th></tr></thead><tbody>{authors.filter(p=>p.handle.toLowerCase().includes(search.toLowerCase())).slice(0,100).map(p=><tr key={p.id}><td><button className={styles.link} onClick={()=>setSelected(p.id)}>@{p.handle}</button></td><td>{p.posts[0].posted_at.slice(0,10)}</td><td>{p.posts.length}</td><td>{p.participants}</td></tr>)}</tbody></table></div>{!authors.length&&<p className={styles.empty}>No authors found in this period.</p>}<p className={`${styles.muted} mt-3`}>Up to 100 matching authors. First found is not first ever. Select the buildup dates on The Run to focus on pre-breakout posts.</p>{meta?.tracking&&<details><summary>Current follower growth, bio matches & tracking</summary><p className={styles.coverageNote}>These ongoing profile measurements use their own recent observation periods, independently of the historical date selection above.</p><CryptoInfluencerPanel data={meta.tracking}/></details>}</>}
   {tab==='network'&&<><div className={styles.toolbar}><div><h3>How attention connected</h3><p className={styles.muted}>Arrows point from the person posting to the account they referenced.</p></div><select aria-label="Network interaction type" value={kind} onChange={e=>{setKind(e.target.value);setEdgeSelection(null);}}>{['all','quote','repost','reply','mention'].map(k=><option key={k} value={k}>{k==='all'?'All interactions':k}</option>)}</select></div><p className={styles.muted}>{graph.nodes.length} of {graph.total} connected accounts · {graph.links.length} connections shown. Click an account to inspect evidence.</p>
    {!graph.nodes.length?<p className={styles.empty}>No connections captured in this date range.</p>:<svg viewBox="0 0 860 470" role="img" aria-label="Account network arranged by observed connections" className="w-full my-4"><defs><marker id="run-arrow" markerWidth="8" markerHeight="8" refX="16" refY="3" orient="auto"><path d="M0,0 L0,6 L6,3z" fill="#a78bfa"/></marker></defs>{graph.links.map(e=>{const a=positions.get(e.source)!,b=positions.get(e.target)!,key=`${e.source}:${e.target}:${e.kind}`;return <g key={key}><line x1={a.x} y1={a.y} x2={b.x} y2={b.y} stroke={edgeSelection===key?'#fbbf24':'#a78bfa'} strokeOpacity={edgeSelection===key?1:.3} strokeWidth={1+Math.min(4,Math.log2(e.weight+1))} markerEnd="url(#run-arrow)"/><line x1={a.x} y1={a.y} x2={b.x} y2={b.y} stroke="transparent" strokeWidth="12" style={{cursor:'pointer'}} onClick={()=>setEdgeSelection(key)}><title>{names.get(e.source)} → {names.get(e.target)}: {e.kind}</title></line></g>;})}{graph.nodes.map(n=><g key={n.id} tabIndex={0} role="button" aria-label={`Open ${names.get(n.id)}`} onClick={()=>setSelected(n.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(n.id);}}} style={{cursor:'pointer'}}><circle cx={n.x} cy={n.y} r={7+Math.min(9,Math.log2(n.weight+1))} fill="#7dd3fc" stroke="var(--bg-elev)" strokeWidth="3"/><text x={n.x} y={n.y-20} textAnchor="middle" fill="var(--ink)" fontSize="10" paintOrder="stroke" stroke="var(--bg-elev)" strokeWidth="4">{names.get(n.id)?.slice(0,22)}</text></g>)}</svg>}
    {chosenEdge&&<p className={styles.insight}><a href={chosenEdge.evidence} target="_blank" rel="noreferrer">@{names.get(chosenEdge.source)} → @{names.get(chosenEdge.target)} · {chosenEdge.kind} × {chosenEdge.weight} · open source ↗</a></p>}<p className={styles.muted}>Interactions can include criticism. Position reflects displayed links, not verified communities or coordination. Liker identities are not available.</p><details><summary>Connections & source posts</summary><div className={styles.table}><table><thead><tr><th className="text-left">From → to</th><th>Type</th><th>Posts</th></tr></thead><tbody>{graph.links.map(e=><tr key={`${e.source}:${e.target}:${e.kind}`}><td><a href={e.evidence} target="_blank" rel="noreferrer">@{names.get(e.source)} → @{names.get(e.target)} ↗</a></td><td>{e.kind}</td><td>{e.weight}</td></tr>)}</tbody></table></div></details></>}
  </>}
  <details className="mt-6"><summary>Sources, coverage & collection</summary><p className={styles.muted}>Social evidence comes from saved records. Market observations and their original responses are archived in Postgres from public APIs. Viewing and filtering spend no TwitterAPI.io credits. Search results are incomplete; temporal alignment does not establish causation.</p>{market?.investigation&&<p className={styles.coverageNote}>Historical collection: {market.investigation.focus_reason} Each batch allows up to {market.investigation.max_requests} requests. Unsearched windows come first, with priority on the buildup period; additional pages follow in rounds within the existing credit ceiling.</p>}{meta?.pilot&&<p className={styles.muted}>Live pilot: {meta.pilot.reserved_credits.toLocaleString()} / {meta.pilot.credit_limit.toLocaleString()} credits reserved. {meta.pilot.outstanding>0?'Collection is paused for an outstanding or uncertain request.':''}</p>}{meta?.history&&<p className={styles.muted}>History: {meta.history.campaign.reserved_credits.toLocaleString()} / {meta.history.campaign.credit_limit.toLocaleString()} reserved.</p>}{coin==='ZCAT'&&<p className={`${styles.muted} break-words`}>Contract HcRLc9VDgjLeK154xDawfb1dmVJ98DoSqcwTHGqiDeJR is matched against pool token relationships and <a className="underline" href="https://bigone.zendesk.com/hc/en-us/articles/62063867754777-BigONE-Alpha-Lists-ZCAT-Anonymous-Cat" target="_blank" rel="noreferrer">BigONE’s September 9 listing announcement</a>. Default pool: pinned when first archived, initially the oldest among the five most liquid returned pools. Historical liquidity is not in these candles; pool prices and volume are not token-wide aggregates.</p>}</details>
  {person&&<CryptoAccountDrawer key={person.id} person={person} tracking={meta?.tracking??null} onClose={()=>setSelected(null)}/>}
 </section>;
}
