"use client";
import {useEffect,useMemo,useState} from 'react';
import type {CoinFinding} from '@/lib/crypto-coin-discovery';
import styles from './crypto-research.module.css';
type Data={coins:CoinFinding[];loaded:number;total:number;unfinished:number;version:string;from:string;to:string};
export function CryptoCoinDiscovery(){
 const [from,setFrom]=useState('2026-09-01'),[to,setTo]=useState(new Date().toISOString().slice(0,10)),[scope,setScope]=useState('all'),[search,setSearch]=useState(''),[limit,setLimit]=useState(20),[retry,setRetry]=useState(0),[data,setData]=useState<Data|null>(null),[error,setError]=useState('');
 useEffect(()=>{const c=new AbortController();setData(null);setError('');if(!from||!to||from>to){setError('Choose a valid date range.');return;}fetch(`/api/market/crypto/coin-discovery?from=${from}&to=${to}`,{signal:c.signal}).then(async r=>{const b=await r.json();if(!r.ok||!b.ok)throw Error();setData(b.data);}).catch(()=>{if(!c.signal.aborted)setError('Could not load discoveries. Check the date range and retry.');});return()=>c.abort();},[from,to,retry]);
 const coins=useMemo(()=>(data?.coins??[]).filter(c=>(scope==='all'||(scope==='tracked'?c.tracked:!c.tracked))&&`${c.symbol} ${c.address??''} ${c.network}`.toLowerCase().includes(search.toLowerCase())),[data,scope,search]);
 return <section aria-label="Coin discovery"><h3>Coins appearing in watcher posts</h3><p className={styles.muted}>Find reported purchases, sales and trading activity. Ranked by distinct reporting accounts, then activity reports. Uses saved posts; no additional X or AI credits.</p>
 <div className={styles.secondaryTabs} aria-label="Discovery scope">{[['all','All coins'],['tracked','Our tracked coins'],['new','Newly discovered']].map(([id,label])=><button key={id} aria-pressed={scope===id} onClick={()=>{setScope(id);setLimit(20);}}>{label}</button>)}</div>
 <div className={styles.discoveryControls}><label>From (UTC)<input className={styles.control} type="date" value={from} max={to} onChange={e=>{setFrom(e.target.value);setLimit(20);}}/></label><label>Through (UTC)<input className={styles.control} type="date" value={to} min={from} onChange={e=>{setTo(e.target.value);setLimit(20);}}/></label><label>Find a coin<input className={styles.control} type="search" value={search} placeholder="Ticker, contract or network" onChange={e=>{setSearch(e.target.value);setLimit(20);}}/></label><button className={styles.control} onClick={()=>setRetry(n=>n+1)}>Refresh</button></div>
 <p className={styles.coverageNote}>Ticker-only groups can contain unrelated assets. “Our tracked coins” includes possible name/ticker matches; only a tracked contract match identifies our configured token. “Newly discovered” means outside our watchlist, not newly launched. Reports are not blockchain-verified.</p>
 {error?<p role="alert">{error} <button className={styles.control} onClick={()=>setRetry(n=>n+1)}>Retry</button></p>:!data?<p role="status">Extracting coins from saved posts…</p>:<><p className={styles.muted}>{coins.length} candidate groups · {data.loaded.toLocaleString()} non-repost posts analyzed{data.total>data.loaded?` of ${data.total.toLocaleString()}; newest 10,000 only`:''}. {data.unfinished} unfinished collection windows. Daily counts reflect collected mentions, not market-wide growth.</p>
 {!coins.length&&<p className={styles.empty}>No matching coin references in the saved posts for these filters. Try all coins or a wider date range.</p>}
 <div className={styles.accountRows}>{coins.slice(0,limit).map((c,i)=><article key={c.key}><div className={styles.mobileAccountHeader}><strong>{i+1}. {c.symbol}</strong><span className={styles.muted}>{c.network==='Unknown'?'Network unresolved':c.network}</span></div><p className={styles.muted}>{c.identity}{c.tracked?' · Watchlist match':''}</p>{c.address&&<p className={styles.discoveryContract}>{c.address}</p>}
 <dl className={styles.discoveryMetrics}><div><dt>Reporting accounts</dt><dd>{c.accounts}</dd></div><div><dt>Saved posts</dt><dd>{c.posts}</dd></div><div><dt>Buy reports</dt><dd>{c.buys}</dd></div><div><dt>Sell reports</dt><dd>{c.sells}</dd></div></dl>
 <p className={styles.muted}>{c.accumulation} accumulation · {c.volume} volume · {c.launches} launch reports · {c.context} context-only reports. {c.repeatedReports} repeated reports consolidated.</p>
 <details><summary>Inspect evidence & daily mentions</summary><p className={styles.muted}>First saved mention in selection: {c.first.slice(0,10)}. Latest: {c.last.slice(0,10)}. These are observation dates, not a launch date.</p><table className={styles.discoveryTable}><caption>Collected mentions by UTC day</caption><thead><tr><th scope="col">Day</th><th scope="col">Posts</th></tr></thead><tbody>{c.daily.map(d=><tr key={d.day}><td>{d.day}</td><td>{d.posts}</td></tr>)}</tbody></table><p className={styles.muted}>Up to eight recent source posts. Action counts consolidate matching transaction links or identical text on the same day; distinct reports may still describe the same trade.</p>{c.examples.map(p=><div key={p.id} className={styles.discoveryEvidence}><p><strong>{p.role==='Context'?'Context mention':p.action}</strong>{p.amount?` · reported ${p.amount}`:''} · @{p.handle}</p><p className={styles.postFullText}>{p.text}</p><a className={styles.link} href={p.url} target="_blank" rel="noreferrer">{p.posted_at.slice(0,16).replace('T',' ')} UTC · Open source ↗</a></div>)}</details></article>)}</div>
 {coins.length>limit&&<button className={styles.control} onClick={()=>setLimit(n=>n+20)}>Show next 20 coins</button>}
 <details className={styles.methodology}><summary>Extraction rules & limitations</summary><p className={styles.muted}>Version {data.version}. Finds cashtags, configured project names, labelled contracts and recognized explorer token URLs. Wallet addresses and pair URLs are not automatically treated as token contracts. Explicit purchase/sale targets take priority over contextual mentions. Unknown names without cashtags can be missed; shortened links are not expanded. A contract reported in a post is unverified; an unknown EVM network remains unresolved. Ticker-only candidate groups never merge into contract groups. Multiple ambiguous assets remain mentions. Reposts and duplicate post IDs are excluded. No price, volume-growth or investment score is inferred. Discoveries are recalculated from database records when this view loads; they do not automatically add coins to paid collection.</p></details></>}
 </section>;
}
