"use client";
import {useEffect,useState} from 'react';
import {CryptoWatcherFeed} from './crypto-watcher-feed';
import type {Watcher} from '@/lib/crypto-watchers';
import styles from './crypto-research.module.css';
type Data={accounts:Watcher[];loaded:number;total:number;candidates:number;asOf?:string};
function WatcherRankings({coin}:{coin:string}){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{const controller=new AbortController();setData(null);setError('');fetch(`/api/market/crypto/watchers?coin=${coin}`,{signal:controller.signal}).then(async r=>{const b=await r.json();if(!r.ok||!b.ok)throw Error();setData(b.data);}).catch(()=>{if(!controller.signal.aborted)setError('Could not load saved watcher evidence.');});return()=>controller.abort();},[coin,retry]);
 return <section aria-label="Whale and volume watchers"><h3>Whale & volume watchers</h3><p className={styles.muted}>{coin==='ALL'?'Across all five coins':coin} · full saved history · no X credits used.</p><p className={styles.coverageNote}>Accounts reporting on wallets and trading volume. These are evidence-based candidates, not verified whales or endorsements. Numeric claims have not been checked against blockchain data.</p>
 {error?<p role="alert">{error} <button className={styles.control} onClick={()=>setRetry(n=>n+1)}>Retry</button></p>:!data?<p role="status">Reviewing saved posts…</p>:<>
 <p className={styles.muted}>Top {data.accounts.length} of {data.candidates} candidates · {data.loaded.toLocaleString()} saved posts examined{data.total>data.loaded?` of ${data.total.toLocaleString()} available; newest records only`:''}.</p>
 {!data.accounts.length&&<p className={styles.empty}>No supported watcher candidates in this selection. A whale keyword alone does not qualify.</p>}
 <div className={styles.accountRows}>{data.accounts.map((a,i)=><article key={a.id}><div className={styles.mobileAccountHeader}><a className={styles.link} href={`https://x.com/i/user/${a.id}`} target="_blank" rel="noreferrer">{i+1}. @{a.handle}</a><span className={styles.muted}>{a.followers==null?'Followers unavailable':Intl.NumberFormat('en',{notation:'compact',maximumFractionDigits:1}).format(a.followers)+' followers'}</span></div><p><strong>{a.category}</strong> · {a.confidence}{!a.specialist?' · Occasional commentator':''}</p><p className={styles.muted}>{a.matched} qualifying posts / {a.total} coin posts · {a.days} days · Mentioned: {a.coins.join(', ')}{a.templated?' · Repeated alert format':''}</p><details><summary>Why this account? View source posts</summary><p className={styles.muted}>{a.whalePosts} whale-activity posts · {a.volumePosts} volume posts · {a.linked} posts link to recognized data/explorer sites. Rankings favor repeated numeric reports and multiple days, rather than follower count. Links and amounts are evidence to inspect, not verification.{a.templated?' Similar formatting may indicate an alert feed; automation is not established.':''}</p>{a.bio&&<p className={styles.muted}>Saved bio: {a.bio}</p>}{a.examples.map(p=><div key={p.id}><p className={styles.postFullText}>{p.text}</p><a className={styles.link} href={p.url} target="_blank" rel="noreferrer">{p.day} · {p.kind} · Open source ↗</a></div>)}<p className={styles.muted}>Followers observed {a.followersObserved?.slice(0,10)??'date unavailable'}. Reporting activity does not establish market impact.</p></details></article>)}</div>
 </>}
 <details className={styles.methodology}><summary>Ranking method & limitations</summary><p className={styles.muted}>Non-repost posts must match a tracked coin, contain whale/wallet activity or trading-volume language, and include a numeric amount. Reposts and duplicate post IDs are excluded. Repeated observations, distinct days, varied formats, source links and relevant bios contribute to the ranking. Dedicated reporting/alert profiles receive priority. Non-specialists need at least three numeric reports. A mentioned coin may be a comparison or trading pair, rather than the asset whose activity is reported. Followers break ties only. English and selected Chinese phrases are supported; other wording may be missed. “Provisional” means fewer than three qualifying posts or fewer than two observed days. Repeated numeric alerts can still be promotional or inaccurate.</p></details>
 </section>;
}

export function CryptoWatchers({coin}:{coin:string}){
 const [view,setView]=useState('feed');
 return <><div className={styles.secondaryTabs} aria-label="Watcher view"><button aria-pressed={view==='feed'} onClick={()=>setView('feed')}>Latest posts</button><button aria-pressed={view==='rankings'} onClick={()=>setView('rankings')}>Account rankings</button></div>{view==='feed'?<CryptoWatcherFeed/>:<WatcherRankings coin={coin}/>}</>;
}
