"use client";
import {useEffect,useState} from 'react';
import {ROLES,type Voice} from '@/lib/crypto-voices';
import styles from './crypto-research.module.css';
type Snapshot={week:string;created_at:string;model:string;selection:{id:string;handle:string;role:string}[];baseline:{reach:string[];posting:string[]};evaluation:null|{evaluated_at:string;days:number;groups:Record<string,{accounts:number;active:number;newPosts:number;newInteractors:number}>}};
type Data={anchor:string|null;loaded:number;total:number;eligible:number;excluded:number;unfinished:number;voices:Voice[];snapshots:Snapshot[];source?:string;computedAt?:string};
export function CryptoVoices({coin}:{coin:string}){
 const [data,setData]=useState<Data|null>(null),[role,setRole]=useState<string>(ROLES[0]),[error,setError]=useState(''),[retry,setRetry]=useState(0),[search,setSearch]=useState('');
 useEffect(()=>{const c=new AbortController();setData(null);setError('');fetch(`/api/market/crypto/voices?coin=${coin}`,{signal:c.signal}).then(async r=>{const b=await r.json();if(!r.ok||!b.ok)throw Error();setData(b.data);}).catch(()=>{if(!c.signal.aborted)setError('Could not load voice evidence.');});return()=>c.abort();},[coin,retry]);
 const rows=(data?.voices??[]).filter(v=>v.scores[role]>0&&v.handle.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>b.scores[role]-a.scores[role]||a.first.localeCompare(b.first)).slice(0,30);
 return <section aria-label="Voice roles"><h3>Find the right kind of voice</h3><p className={styles.muted}>{coin} · full saved history · candidates for review, not proven market influence.</p><div className={styles.secondaryTabs}>{ROLES.map(r=><button key={r} aria-pressed={role===r} onClick={()=>setRole(r)}>{r}</button>)}</div><label>Find an account<input className={styles.control} type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Account handle"/></label>
 {error?<p role="alert">{error} <button onClick={()=>setRetry(n=>n+1)}>Retry</button></p>:!data?<p role="status">Reviewing identity and voice evidence…</p>:<><p className={styles.coverageNote}>{data.anchor?`First saved exact-contract evidence: ${data.anchor.slice(0,16).replace('T',' ')} UTC. Earlier ticker-only posts are excluded.`:coin==='ZEC'?'Zcash is native; no token-contract anchor. Early-discoverer ranking is unavailable.':'No exact-contract anchor yet. Ticker-only early voices are withheld.'} This is not a verified launch date.</p><p className={styles.muted}>{data.eligible.toLocaleString()} eligible non-repost posts · {data.excluded.toLocaleString()} posts excluded by identity rules · {data.unfinished} unfinished search windows{data.total>data.loaded?` · only earliest ${data.loaded.toLocaleString()} of ${data.total.toLocaleString()} loaded`:''}{data.source==='snapshot'&&data.computedAt?` · ranked from every saved row at ${data.computedAt.slice(0,16).replace('T',' ')} UTC`:''}.</p><p className={styles.muted}>{role==='Early discoverers'?'First seven days after the saved contract anchor; exact-contract posts receive priority.':role==='Original analysis'?'Original posts with explanatory or analytical wording; repeated text earns no additional analysis credit.':role==='Amplifiers'?'Subsequent replies and quotes from distinct accounts, with a limited audience-size contribution.':role==='Project / platform'?'Explicitly configured project/platform handles; these are interested sources, not independent endorsement.':'Reporting-feed candidates inferred from handles or repeated templates; automation is not verified.'}</p>
 <div className={styles.accountRows}>{rows.map(v=><article key={v.id}><div className={styles.mobileAccountHeader}><strong>@{v.handle}</strong><span>{v.followers==null?'Audience unknown':v.followers.toLocaleString()+' followers'}</span></div><p>{v.identity}</p><p className={styles.muted}>First saved {v.first.slice(0,10)} · {v.posts} posts · {v.analysis} distinct analysis candidates · {v.subsequent} subsequent reply/quote accounts · {v.repeatPercent}% repeated formats</p><details><summary>Why this account? Inspect evidence</summary><p className={styles.muted}>Latest saved followers are not historical reach. Replies and quotes may disagree. Distinct accounts may be coordinated. Text heuristics do not verify originality, factual accuracy or causal impact.</p>{v.examples.map(p=><div className={styles.discoveryEvidence} key={p.id}><p className={styles.postFullText}>{p.text}</p><a className={styles.link} href={p.url} target="_blank" rel="noreferrer">{p.posted_at.slice(0,16).replace('T',' ')} UTC · {p.kind} · Open source ↗</a></div>)}</details></article>)}</div>{!rows.length&&<p className={styles.empty}>Insufficient evidence for this role. Try another role or clear the account search.</p>}
 <details className={styles.methodology}><summary>Weekly validation & frozen shortlists</summary><p className={styles.muted}>Each weekly shortlist is frozen when created, alongside follower-count and posting-volume baselines. After seven days, compare future collected activity and distinct incoming accounts. All shortlisted candidates are retained, including inactive ones. This measures subsequent attention in our sample, not investment returns or proven predictive ability; missing coverage affects every comparison.</p>{!data.snapshots.length&&<p>Awaiting the first scheduled snapshot.</p>}{data.snapshots.map(s=><div key={s.week}><h4>Week of {s.week.slice(0,10)}</h4><p>{s.selection.length} candidates frozen {s.created_at.slice(0,10)} · {s.model}</p><p>{s.selection.map(v=>'@'+v.handle+' ('+v.role+')').join(', ')}</p>{!s.evaluation?<p>Seven-day follow-up pending.</p>:<table className={styles.discoveryTable}><thead><tr><th>Group</th><th>Active / selected</th><th>New posts</th><th>Incoming accounts*</th></tr></thead><tbody>{Object.entries(s.evaluation.groups).map(([name,g])=><tr key={name}><td>{name}</td><td>{g.active} / {g.accounts}</td><td>{g.newPosts}</td><td>{g.newInteractors}</td></tr>)}</tbody></table>}</div>)}<p className={styles.muted}>*Sum of per-candidate distinct incoming accounts; audiences overlap. The 20-account daily cohort mixes large audiences, early voices, analysis candidates and amplifiers. Seven-day growth remains unavailable until comparable observations exist.</p></details></>}
 </section>;
}
