import test from 'node:test';import assert from 'node:assert/strict';
import {rankVoices,voiceEvidence,CONTRACTS,type VoicePost} from './crypto-voices.ts';
import {rankWatchers} from './crypto-watchers.ts';
const p:VoicePost={id:'1',author_id:'a',handle:'early',text:CONTRACTS.ZCAT,posted_at:'2026-08-30T10:00:00Z',kind:'original',url:'https://x.com/i/status/1',edges:[],followers:100};
test('pre-anchor ticker collisions and TON chatter cannot lead early voices',()=>{const rows=[{...p,id:'0',text:'$ZCAT on TON',posted_at:'2026-07-25T10:00:00Z'},p,{...p,id:'3',text:'$ZCAT on TON',posted_at:'2026-09-01T00:00:00Z'}];assert.equal(voiceEvidence(rows,'ZCAT').eligible.length,1);assert.equal(rankVoices(rows,'ZCAT').voices[0].first,'2026-08-30T10:00:00.000Z');});
test('no contract anchor withholds meme-token rankings; native ZEC accepts bare ticker',()=>{assert.equal(rankVoices([{...p,text:'$ZCAT'}],'ZCAT').voices.length,0);assert.equal(rankVoices([{...p,text:'ZEC supply'}],'ZEC').voices.length,1);});
test('repeated analysis earns one credit; reporting feeds are separated',()=>{const text='$ZCAT because liquidity and supply explain the mechanism. '.repeat(5);const r=rankVoices([p,{...p,id:'2',text},{...p,id:'3',text},{...p,id:'4',handle:'whalewatchalert',author_id:'b',text}], 'ZCAT');assert.equal(r.voices.find(v=>v.id==='a')!.analysis,1);assert.equal(r.voices.find(v=>v.id==='b')!.scores['Early discoverers'],0);assert.equal(r.voices.find(v=>v.id==='b')!.role,'Reporting feeds');});
test('subsequent quote accounts deduplicate and future observations cannot enter frozen cutoff',()=>{const q={...p,id:'2',author_id:'b',text:'$ZCAT',kind:'quote',posted_at:'2026-08-31T00:00:00Z',edges:[{target_id:'a',target:'early',kind:'quote'}]};assert.equal(rankVoices([p,q,{...q,id:'3'}],'ZCAT').voices.find(v=>v.id==='a')!.subsequent,1);assert.equal(rankVoices([p,q],'ZCAT','2026-08-30T12:00:00Z').voices.length,1);});
test('watcher rankings normalize native database dates',()=>{const r=rankWatchers([{...p,posted_at:new Date(p.posted_at),followers_observed_at:new Date(p.posted_at),handle:'whalewatchalert',text:'$ZCAT whale bought $1000',coins:['ZCAT']} as any]);assert.equal(r.length,1);});
