import test from 'node:test';
import assert from 'node:assert/strict';
import {extractCoins,discoverCoins,type DiscoveryPost} from './crypto-coin-discovery.ts';
const p:DiscoveryPost={id:'1',author_id:'a',handle:'alice',text:'A $JIMOTHY whale just bought $9.97K of $CATE at $58.95M MC.',posted_at:'2026-09-15T10:00:00Z',kind:'original',url:'https://x.com/i/status/1'};
test('purchase target is distinct from wallet association and market cap',()=>{const r=extractCoins(p.text);assert.equal(r.find(x=>x.symbol==='CATE')?.action,'Buy');assert.equal(r.find(x=>x.symbol==='CATE')?.amount,'$9.97K');assert.equal(r.find(x=>x.symbol==='JIMOTHY')?.role,'Context');assert.equal(r.length,2);});
test('same ticker contracts remain separate; ticker-only is unresolved',()=>{const a='0x'+'a'.repeat(40),b='0x'+'b'.repeat(40);const r=discoverCoins([{...p,text:`$CAT CA: ${a}`},{...p,id:'2',text:`$CAT CA: ${b}`},{...p,id:'3',text:'$CAT'}]);assert.equal(r.length,3);assert.ok(r.every(x=>x.network==='Unknown'));assert.equal(r.filter(x=>x.address).length,2);});
test('wallets and tx hashes are not contracts; explicit explorer token links are',()=>{const a='0x'+'a'.repeat(40);assert.equal(extractCoins(`wallet ${a} bought $CAT`)[0].address,null);assert.equal(extractCoins('https://etherscan.io/tx/0x'+'a'.repeat(64)).length,0);assert.equal(extractCoins(`$CAT https://basescan.org/token/${a}`)[0].network,'Base');});
test('known contract maps to watchlist and native Zcash has no invented contract',()=>{assert.equal(extractCoins('CA: HcRLc9VDgjLeK154xDawfb1dmVJ98DoSqcwTHGqiDeJR')[0].symbol,'ZCAT');assert.equal(extractCoins('Zcash is interesting')[0].address,null);});
test('duplicates, reposts and repeated transaction reports do not inflate actions',()=>{const text='bought $20K of $CAT https://etherscan.io/tx/0x'+'a'.repeat(64);const r=discoverCoins([{...p,text},{...p,text},{...p,text,id:'2',author_id:'b'},{...p,text,id:'3',kind:'repost'}])[0];assert.equal(r.posts,2);assert.equal(r.accounts,2);assert.equal(r.buys,1);assert.equal(r.repeatedReports,1);});
test('multi-asset general volume comments are not attributed to every coin',()=>{const r=extractCoins('$CAT and $DOG volume $20M');assert.ok(r.every(c=>c.action==='Mention'));assert.ok(r.every(c=>c.role==='Context'));});
test('sales and launches have separate action counts',()=>{const r=discoverCoins([{...p,text:'sold $5K of $CAT'},{...p,id:'2',text:'New pair: $DOG'}]);assert.equal(r.find(c=>c.symbol==='CAT')?.sells,1);assert.equal(r.find(c=>c.symbol==='DOG')?.launches,1);});

test('token quantities do not become dollar amounts and mixed actions stay unclassified',()=>{assert.equal(extractCoins('bought 500 $CAT')[0].amount,null);assert.equal(extractCoins('bought $5K of $CAT then sold $2K of $CAT')[0].action,'Mention');});
test('dex paid token labels are extracted without treating the quote currency as target',()=>{const r=extractCoins('Dex paid: Launch Express (LE) / ETH CA: 0x'+'a'.repeat(40));assert.equal(r.length,1);assert.equal(r[0].symbol,'LE');assert.equal(r[0].action,'Launch');});
