'use client';
import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import {Area,AreaChart,Bar,BarChart,CartesianGrid,Line,LineChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {BP_MINT,dayOffset,mechanicalChanges,numeric,point,qualityFor,rollingIssuance,sortRows,windowChange,type MonitorData,type Row} from '@/lib/backpack';
import s from './monitor.module.css';
import {GrowthOverview} from './growth-overview';
import {ResearchContext} from './research-context';
const periods=['7D','30D','90D','180D','YTD','1Y','ALL'];
const money=(v:unknown)=>numeric(v)===null?'N/A':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',notation:'compact',maximumFractionDigits:2}).format(Number(v));
const count=(v:unknown)=>numeric(v)===null?'N/A':new Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:1}).format(Number(v));
const pct=(v:unknown)=>numeric(v)===null?'N/A':`${Number(v).toFixed(2)}%`;
const stamp=(v:unknown)=>v?String(v).replace('T',' ').slice(0,19)+' UTC':'Not captured';
function Delta({value,label}:{value:number|null;label:string}){return <span className={value===null?s.muted:value>=0?s.positive:s.negative}>{label} {value===null?'N/A':`${value>=0?'+':''}${value.toFixed(2)}%`}</span>;}
function Provenance({data,field,assetId}:{data:MonitorData;field:string;assetId?:string}){
 const q=qualityFor(data,field,assetId);
 const stale=!!data.asOf&&(Date.now()-Date.parse(`${data.asOf}T00:00:00Z`)>48*3600*1000);
 return <details className={s.provenance}><summary>{stale?'Stale':q.status} · source & method</summary><div><b>{q.source}</b><p>{q.calculation}</p><p>{q.limitation}</p><small>{stamp(q.observed_at)}</small></div></details>;
}
function Chart({rows,field,title,format=money,kind='area',subtitle}:{rows:Row[];field:string;title:string;format?:(v:unknown)=>string;kind?:'area'|'bar'|'line';subtitle?:string}){
 const points=rows.map(r=>({date:String(r.date).slice(0,10),value:numeric(r[field])}));
 const any=points.some(p=>p.value!==null);
 const chartChildren=[<CartesianGrid key="grid" vertical={false} stroke="#e4e9ef"/>,<XAxis key="x" dataKey="date" tick={{fontSize:10}} tickFormatter={d=>String(d).slice(5)} minTickGap={30}/>,<YAxis key="y" width={65} tick={{fontSize:10}} tickFormatter={format}/>,<Tooltip key="tooltip" formatter={v=>format(v)} labelFormatter={v=>`${v} · UTC snapshot`}/>];
 return <section className={s.panel}><div className={s.panelTitle}><h2>{title}</h2><span>{subtitle}</span></div>{any?<div className={s.chart}><ResponsiveContainer width="100%" height="100%">{kind==='bar'?<BarChart data={points}>{chartChildren}<Bar dataKey="value" fill="#43657e"/></BarChart>:kind==='line'?<LineChart data={points}>{chartChildren}<Line dataKey="value" stroke="#21776c" strokeWidth={2} connectNulls={false} dot={points.length<3}/></LineChart>:<AreaChart data={points}>{chartChildren}<Area dataKey="value" stroke="#21776c" fill="#dfeeea" strokeWidth={2} connectNulls={false} dot={points.length<3}/></AreaChart>}</ResponsiveContainer></div>:<div className={s.empty}><strong>Awaiting reliable observations</strong><p>History begins with captured daily snapshots. Missing dates and unknown values remain gaps.</p></div>}</section>;
}
function KPI({title,field,rows,day,data,format=money,assetId}:{title:string;field:string;rows:Row[];day:string;data:MonitorData;format?:(v:unknown)=>string;assetId?:string}){
 const value=point(rows,day)?.[field];
 return <section className={s.kpi}><div>{title}</div><strong>{format(value)}</strong><div className={s.deltas}><Delta label="7D" value={windowChange(rows,day,field,7)}/><Delta label="30D" value={windowChange(rows,day,field,30)}/></div>
 <div className={s.spark}>{rows.some(r=>numeric(r[field])!==null)&&<ResponsiveContainer width="100%" height={28}><LineChart data={rows.slice(-30).map(r=>({v:numeric(r[field])}))}><Line dataKey="v" stroke="#698c8a" strokeWidth={1.5} dot={false} connectNulls={false}/></LineChart></ResponsiveContainer>}</div><small>{day||'Not captured'}</small><Provenance data={data} field={field} assetId={assetId}/></section>;
}
const columns:[string,string,(v:unknown)=>string][]=[['token_symbol','Ticker',String],['underlying_symbol','Underlying',String],['solana_mint','Mint',v=>String(v).slice(0,5)+'…'+String(v).slice(-5)],['reference_aum_usd','AUM',money],['aum30','AUM 30D',pct],['issuance30','Issuance 30D',money],['holders_over_100','Wallets ≥$100',count],['holders30','Holders 30D',pct],['daily_swap_volume_usd','DEX 24H',money],['volume_to_aum_ratio','Volume/AUM',v=>numeric(v)===null?'N/A':`${Number(v).toFixed(2)}×`],['after_hours_volume_pct','Market closed',pct],['defi_utilization_pct','DeFi use',pct],['premium_discount_pct','Premium / discount',pct],['quote_10k_price_impact','$10K impact',pct],['quote_50k_price_impact','$50K impact',pct],['launch_date','Launch',v=>v?String(v).slice(0,10):'N/A']];
export function BackpackMonitor({assetId}:{assetId?:string}){
 const [data,setData]=useState<MonitorData|null>(null),[error,setError]=useState(''),[period,setPeriod]=useState('90D'),[search,setSearch]=useState(''),[sort,setSort]=useState('reference_aum_usd'),[desc,setDesc]=useState(true),[admin,setAdmin]=useState(false),[refresh,setRefresh]=useState('');
 useEffect(()=>{let active=true;fetch(`/api/market/crypto/backpack${assetId?`?asset=${assetId}`:''}`).then(async r=>{if(!r.ok)throw new Error('Could not load stored observations.');return r.json();}).then(d=>{if(active)setData(d);}).catch(e=>{if(active)setError(e.message);});fetch('/api/admin/backpack').then(r=>{if(active)setAdmin(r.ok);}).catch(()=>{});return()=>{active=false;};},[assetId]);
 const day=data?.asOf??'',asset=data?.assets.find(a=>String(a.id)===assetId);
 const rows=useMemo(()=>data?(assetId?data.history.filter(h=>String(h.asset_id)===assetId):data.ecosystem):[],[data,assetId]);
 const visible=useMemo(()=>{if(!day)return rows;const start=period==='ALL'?'0000':period==='YTD'?day.slice(0,4)+'-01-01':dayOffset(day,-(period==='1Y'?365:Number(period.replace('D','')))+1);return rows.filter(r=>String(r.date).slice(0,10)>=start);},[rows,day,period]);
 async function refreshNow(){setRefresh('Queuing…');try{const r=await fetch('/api/admin/backpack',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'refresh'})});const v=await r.json();setRefresh(v.message??v.error);}catch{setRefresh('Refresh could not be queued.');}}
 if(error)return <div className={s.notice} role="alert">{error} <button onClick={()=>window.location.reload()}>Retry</button></div>;
 if(!data)return <div className={s.loading}>Loading Backpack research observations…</div>;
 const latest=point(rows,day),bp=data.bp.at(-1),meaningful=assetId?'holders_over_100':'meaningful_holders',isBp=asset?.asset_type==='bp';
 const computed=(scope:number,metric:string,period:number)=>numeric(data.analytics?.find(r=>Number(r.scope_asset_id)===scope&&r.metric===metric&&Number(r.period_days)===period)?.value);
 const table=sortRows(data.assets.filter(a=>a.asset_type!=='bp').map(a=>{const h=data.history.filter(r=>String(r.asset_id)===String(a.id));return {...a,aum30:data.analytics?computed(Number(a.id),'reference_aum_usd_growth_pct',30):windowChange(h,day,'reference_aum_usd',30),holders30:data.analytics?computed(Number(a.id),'holders_over_100_growth_pct',30):windowChange(h,day,'holders_over_100',30),issuance30:data.analytics?computed(Number(a.id),'net_issuance_usd',30):rollingIssuance(h,day,30)};}),sort,desc).filter(a=>`${a.token_symbol} ${a.underlying_symbol} ${a.solana_mint}`.toLowerCase().includes(search.toLowerCase()));
 return <div className={s.root}>
 <header className={s.header}><div><div className={s.eyebrow}>CRYPTO RESEARCH / ON-CHAIN EVIDENCE</div><h1>{assetId?`${asset?.token_symbol??'Asset'} · Research detail`:'Backpack Thesis Monitor'}</h1><p>Capital, ownership and financial use. Totals cover registered securities, not necessarily the full Backpack universe.</p></div><div className={s.actions}><Link href="/market/crypto">Crypto workbench</Link>{assetId&&<Link href="/market/crypto/backpack">All Backpack assets</Link>}{admin?<><button onClick={refreshNow}>Refresh Now</button><Link href="/admin/backpack">Manage registry</Link></>:<Link href="/admin/backpack">Admin</Link>}</div></header>
 {refresh&&<p role="status" className={s.notice}>{refresh}</p>}
 <div className={s.strip}><span><i className={day?s.dot:s.offDot}/> {day?`Snapshot ${day} UTC`:'No captured snapshots'}</span><span>Daily target 00:30 UTC</span><span>Trading window: previous UTC day</span><span>Meaningful = wallet value ≥$100</span></div>
 {data.status!=='ready'&&<div className={s.notice}><strong>{data.status==='schema_pending'?'Collector schema awaiting initialization':data.status==='not_configured'?'Data connection not configured':'Awaiting first daily capture'}</strong><p>No sample values are shown. Approved security mints and provider access are required before AUM and adoption history can populate.</p></div>}
 {!assetId&&table.length===0&&<div className={s.notice}><strong>No approved Backpack securities captured yet.</strong><p>Exchange-listed stocks are not automatically on-chain securities. Add each mint with source evidence through the registry. BP is tracked separately below.</p></div>}
 {day&&Date.now()-Date.parse(`${day}T00:00:00Z`)>48*3600*1000&&<div className={s.notice}>Stale: the latest stored capture is more than 48 hours old.</div>}
 {asset&&<div className={s.identity}><b>{String(asset.token_name)}</b><span>{String(asset.underlying_symbol??'BP utility token')} · {String(asset.underlying_exchange??'Solana')}</span><code>{String(asset.solana_mint)}</code><span>{String(asset.verification_status).replace('_',' ')}</span><a href={String(asset.official_source).startsWith('https://')?String(asset.official_source):undefined} target="_blank" rel="noreferrer">Registry evidence</a></div>}
 {!assetId&&<GrowthOverview data={data}/>}
 <div className={s.kpis}>
 <KPI title={isBp?"BP total supply":"Reference AUM"} field={isBp?"token_supply":"reference_aum_usd"} format={isBp?count:money} rows={rows} day={day} data={data} assetId={assetId}/>
 <KPI title="Meaningful wallets" field={meaningful} rows={rows} day={day} data={data} format={count} assetId={assetId}/>
 <section className={s.kpi}><div>Net on-chain issuance · 30D</div><strong>{money(rollingIssuance(rows,day,30))}</strong><p>7D {money(rollingIssuance(rows,day,7))} · 90D {money(rollingIssuance(rows,day,90))}</p><small>Requires every daily delta · {day||'Not captured'}</small><Provenance data={data} field="net_supply_change_usd" assetId={assetId}/></section>
 <KPI title="DEX volume · total 24H" field="daily_swap_volume_usd" rows={rows} day={day} data={data} assetId={assetId}/>
 <KPI title="DeFi utilization" field="defi_utilization_pct" rows={rows} day={day} data={data} format={pct} assetId={assetId}/>
 <section className={s.kpi}><div>BP · separate ownership thesis</div><strong>{money(bp?.onchain_price)}</strong><p>FDV {money(bp?.fdv_usd)}</p><small>Market cap {money(bp?.market_cap_usd)}</small><p className={s.muted}>Circulating supply is not inferred from total supply.</p></section>
 </div>

 <div className={s.sectionHead}><div><h2>Adoption over time</h2><p>Reference AUM reflects issuance and underlying price changes. Use net issuance to distinguish them.</p></div><div className={s.ranges} aria-label="Chart range">{periods.map(p=><button key={p} aria-pressed={p===period} onClick={()=>setPeriod(p)}>{p}</button>)}</div></div>
 <div className={s.primaryCharts}><Chart rows={visible} field={isBp?"token_supply":"reference_aum_usd"} title={isBp?"BP total supply":"Tracked Backpack security AUM"} format={isBp?count:money} subtitle={isBp?"Finalized supply · tokens":"Reference value · USD"}/><div className={s.sideCharts}><Chart rows={visible} field="net_supply_change_usd" title="Net on-chain issuance" kind="bar" subtitle="Daily supply change × reference price"/><Chart rows={visible} field={meaningful} title="Meaningful holder growth" format={count} kind="line" subtitle="Deduplicated owners · ≥$100"/></div></div>
 {!assetId&&<ResearchContext data={data}/>}
 {!assetId&&<section className={s.panel}><h2>AUM composition</h2><p>Share of tracked security reference AUM · calculated once per capture · {day||'Not captured'}</p><dl className={s.facts}><dt>Largest security share</dt><dd>{pct(computed(0,'top_1_aum_pct',0))}</dd><dt>Top 3 / 5 / 10</dt><dd>{pct(computed(0,'top_3_aum_pct',0))} / {pct(computed(0,'top_5_aum_pct',0))} / {pct(computed(0,'top_10_aum_pct',0))}</dd><dt>Outside top 10</dt><dd>{money(computed(0,'long_tail_aum_usd',0))}</dd></dl></section>}
 {!assetId&&<section className={s.changes}><span className={s.eyebrow}>WHAT CHANGED?</span>{mechanicalChanges(rows,day).map(t=><p key={t}>{t}</p>)}<small>Mechanically derived from stored observations. No thesis score or recommendation.</small></section>}
 <div className={s.twoColumns}><Chart rows={visible} field="daily_swap_volume_usd" title="Trading activity" kind="bar" subtitle="Complete DEX volume only"/><section className={s.panel}><h2>Adoption vs. trading churn</h2><dl className={s.facts}><dt>Reference AUM</dt><dd>{money(latest?.reference_aum_usd)}</dd><dt>On-chain market value</dt><dd>{money(latest?.onchain_market_value_usd)}</dd><dt>30D net issuance / AUM</dt><dd>{numeric(latest?.reference_aum_usd)&&rollingIssuance(rows,day,30)!==null?pct(100*rollingIssuance(rows,day,30)!/Number(latest?.reference_aum_usd)):'N/A'}</dd><dt>Observed swap sample</dt><dd>{money(latest?.observed_swap_volume_usd)} · partial</dd><dt>Multi-asset adoption</dt><dd>{pct(latest?.multi_asset_adoption_pct)}</dd><dt>Wallets with 2+ / 3+ / 5+ assets</dt><dd>{count(latest?.multi_asset_2)} / {count(latest?.multi_asset_3)} / {count(latest?.multi_asset_5)}</dd></dl><p className={s.muted}>Volume is not adoption. Sampled swaps are a lower bound, not market-wide volume. Each security needs ≥$100 per wallet to count toward multi-asset breadth.</p></section></div>
 {!assetId&&<section className={s.panel}><div className={s.sectionHead}><div><h2>Security universe</h2><p>{table.length} registry entries · click a ticker for evidence and history</p></div><input aria-label="Search securities" placeholder="Search ticker, underlying or mint" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className={s.tableWrap}><table><thead><tr>{columns.map(([key,label])=><th key={key} aria-sort={sort===key?(desc?'descending':'ascending'):'none'}><button onClick={()=>{setSort(key);setDesc(sort===key?!desc:true);}}>{label}{sort===key?(desc?' ↓':' ↑'):''}</button></th>)}</tr></thead><tbody>{table.map(a=><tr key={String(a.id)}>{columns.map(([key,,fmt])=><td key={key} title={key==='solana_mint'?String(a[key]):undefined}>{key==='token_symbol'?<Link href={`/market/crypto/backpack/${a.id}`}>{String(a[key])}</Link>:a[key]==null?'N/A':fmt(a[key])}</td>)}</tr>)}</tbody></table>{!table.length&&<p className={s.tableEmpty}>No matching securities. Unverified mints are never inferred from ticker names.</p>}</div></section>}
 {assetId&&<>
 <div className={s.twoColumns}><Chart rows={visible} field="token_supply" title="Token supply" format={count}/><Chart rows={visible} field="premium_discount_pct" title="Market parity · daily observations" format={pct} kind="line" subtitle="Last available equity reference when closed"/></div>
 <section className={s.panel}><h2>Price references</h2><dl className={s.facts}><dt>On-chain</dt><dd>{money(latest?.onchain_price)} · {stamp(latest?.onchain_price_timestamp)}</dd><dt>Underlying</dt><dd>{money(latest?.underlying_price)} · {stamp(latest?.underlying_price_timestamp)}</dd><dt>Underlying session at capture</dt><dd>{latest?.underlying_market_open==null?'Unavailable':latest.underlying_market_open?'Open':'Closed · last available reference'}</dd><dt>Premium / discount</dt><dd>{pct(latest?.premium_discount_pct)}</dd></dl><Provenance data={data} field="premium_discount_pct" assetId={assetId}/></section>
 <section className={s.panel}><h2>Execution quality · both directions</h2><p>Quotes are route availability observations, not executed trades. N/A means no reliable quote.</p><div className={s.tableWrap}><table><thead><tr><th>Size</th><th>Direction</th><th>Expected output</th><th>Impact</th><th>Route legs</th><th>As of</th><th>Status</th></tr></thead><tbody>{[1000,10000,50000,100000].flatMap(size=>['buy','sell'].map(direction=>{const q=data.quotes.find(q=>Number(q.notional_usd)===size&&q.direction===direction);return <tr key={`${size}${direction}`}><td>{money(size)}</td><td>{direction==='buy'?'USDC → token':'Token → USDC'}</td><td>{count(q?.expected_output)}</td><td>{pct(q?.price_impact_pct)}</td><td>{count(q?.route_legs)}</td><td>{stamp(q?.quote_at)}</td><td><details><summary>{String(q?.status??'Unavailable')}</summary><p>{String(q?.limitation??'Quote capture not enabled or unavailable')}</p><pre>{q?.route?JSON.stringify(q.route,null,2):'No route'}</pre></details></td></tr>;}))}</tbody></table></div></section>
 <div className={s.twoColumns}><section className={s.panel}><h2>Holder quality</h2><dl className={s.facts}>{[['holder_count','Nonzero token accounts'],['unique_holders','Unique owners'],['holders_over_100','Wallets ≥$100'],['holders_over_1000','Wallets ≥$1K'],['holders_over_10000','Wallets ≥$10K'],['holders_over_100000','Wallets ≥$100K']].map(([k,label])=><div className={s.factRow} key={k}><dt>{label}</dt><dd>{count(latest?.[k])}</dd></div>)}</dl><Provenance data={data} field="holders" assetId={assetId}/></section><section className={s.panel}><h2>Concentration</h2><table><thead><tr><th>Cohort</th><th>Raw</th><th>Economic</th></tr></thead><tbody>{[10,20,50,100].map(n=><tr key={n}><td>Top {n}</td><td>{pct(latest?.[`top_${n}_holder_pct`])}</td><td>{pct(latest?.[`economic_top_${n}_holder_pct`])}</td></tr>)}</tbody></table><p>Economic concentration excludes confirmed/high-confidence system wallets from numerator and denominator. Unlabeled addresses may still be systems.</p></section></div>
 <section className={s.panel}><h2>Largest observed owners</h2><p>System labels are evidence-backed; unlabeled owners are not identified individuals. Top 100 by token balance.</p><div className={s.tableWrap}><table><thead><tr><th>Wallet</th><th>Tokens</th><th>Reference value</th><th>Label at capture</th><th>Economic cohort</th></tr></thead><tbody>{data.holders.map(h=><tr key={String(h.wallet_address)}><td><a href={`https://solscan.io/account/${h.wallet_address}`} target="_blank" rel="noreferrer">{String(h.wallet_address)}</a></td><td>{count(h.balance_tokens)}</td><td>{money(h.value_usd)}</td><td><details><summary>{String(h.label)}</summary><p>{String(h.label_entity??'Entity not captured')} · {String(h.label_confidence??'Confidence not captured')}</p><p>{String(h.label_source??'Label evidence not captured for this historical row')}</p><small>{stamp(h.label_verified_at)}</small></details></td><td>{h.excluded?'Excluded':'Included / attribution incomplete'}</td></tr>)}</tbody></table></div></section>
 </>}
 {!assetId&&<section className={s.panel}><div className={s.sectionHead}><div><span className={s.eyebrow}>H5 / BP OWNERSHIP</span><h2>BP supply and ownership</h2></div><code className={s.mint}>{BP_MINT}</code></div><div className={s.bpGrid}>{[['token_supply','Total supply',count],['estimated_circulating_supply','Verified circulating amount',count],['holders_over_100','Meaningful holders',count],['whale_count','Economic whales ≥$100K',count],['top_20_holder_pct','Top 20 · raw',pct],['economic_top_20_holder_pct','Top 20 · economic',pct]].map(([k,label,fmt])=><div key={String(k)}><small>{String(label)}</small><strong>{(fmt as (v:unknown)=>string)(bp?.[String(k)])}</strong></div>)}</div><p>BP is separate from tokenized securities. Backpack-associated balances are not labeled as staked. Circulating supply, unlocks and exchange flows require verified sources.</p>{data.assets.filter(a=>a.asset_type==='bp').map(a=><Link key={String(a.id)} href={`/market/crypto/backpack/${a.id}`}>Inspect BP holders and source evidence →</Link>)}<Chart rows={data.bp.filter(r=>period==='ALL'||String(r.date)>=dayOffset(day||new Date().toISOString().slice(0,10),-(period==='1Y'?365:period==='YTD'?366:Number(period.replace('D','')))))} field="economic_top_20_holder_pct" title="BP top-20 economic concentration" format={pct} kind="line"/></section>}
 {(!assetId||isBp)&&<section className={s.panel}><h2>BP economic whale cohorts</h2><p>New/exited whales describe USD threshold crossings, which may be price-driven. Accumulation is the token balance change of yesterday’s whales, including wallets that exited. Verified system wallets on either date are excluded from changes.</p><div className={s.tableWrap}><table><thead><tr><th>Threshold</th><th>Whales</th><th>New since yesterday</th><th>Exited</th><th>Prior cohort accumulation · BP</th><th>Source / method</th></tr></thead><tbody>{(data.whales??[]).filter(r=>r.date===day).sort((a,b)=>Number(a.threshold_usd)-Number(b.threshold_usd)).map(r=><tr key={String(r.threshold_usd)}><td>≥{money(r.threshold_usd)}</td><td>{count(r.whale_count)}</td><td>{count(r.new_whales)}</td><td>{count(r.exited_whales)}</td><td>{count(r.whale_net_accumulation_tokens)}</td><td><details><summary>{String(r.status)} · {String(r.date)}</summary><p>{String(r.source)}</p><p>{String(r.methodology)}</p></details></td></tr>)}</tbody></table></div>{!(data.whales??[]).some(r=>r.date===day)&&<p>No whale cohort capture available. Changes require consecutive complete, priced holder snapshots.</p>}<Provenance data={data} field="whale_cohorts" assetId={assetId}/></section>}
 <section className={s.panel}><h2>Coverage and provenance</h2><p>Verified / Estimated / Partial / Stale / Unavailable. Field coverage is not an investment score. Missing history is never reconstructed from today's balances.</p><details><summary>View latest per-metric evidence ({data.quality.length})</summary><div className={s.tableWrap}><table><thead><tr><th>Metric</th><th>Status</th><th>Source</th><th>Calculation / limitation</th><th>Observed</th></tr></thead><tbody>{data.quality.map((q,i)=><tr key={i}><td>{q.metric}</td><td>{q.status}</td><td>{q.source}</td><td>{q.calculation}<br/>{q.limitation}</td><td>{stamp(q.observed_at)}</td></tr>)}</tbody></table></div></details><details><summary>Collection runs and provider usage</summary><div className={s.tableWrap}><table><thead><tr><th>Started</th><th>Execution</th><th>Attempted / captured / failed / skipped</th><th>Notes</th></tr></thead><tbody>{data.runs.map(r=><tr key={String(r.run_id)}><td>{stamp(r.started_at)}</td><td>{String(r.status)}</td><td>{String(r.assets_attempted)} / {String(r.assets_succeeded)} / {String(r.assets_failed)} / {String(r.assets_skipped)}</td><td>{String(r.source_errors||r.data_quality_warnings)}</td></tr>)}</tbody></table><table><thead><tr><th>Provider</th><th>HTTP requests</th><th>Credits</th><th>Estimated cost</th></tr></thead><tbody>{data.usage.map((u,i)=><tr key={i}><td>{String(u.provider)}</td><td>{count(u.requests)}</td><td>{count(u.credits)}</td><td>{money(u.estimated_cost_usd)}</td></tr>)}</tbody></table></div></details></section>
 <footer className={s.footer}>Research coverage: captured on-chain evidence. Company-reported metrics, customer deposits and investment recommendations are not inferred.</footer>
 </div>;
}
