'use client';
import type {MonitorData,Row} from '@/lib/backpack';
import {numeric} from '@/lib/backpack';
import s from './monitor.module.css';
const pct=(v:unknown)=>numeric(v)===null?'N/A':`${Number(v).toFixed(2)}%`;
const money=(v:unknown)=>numeric(v)===null?'N/A':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',notation:'compact',maximumFractionDigits:1}).format(Number(v));
export function EconomyEvidence({data}:{data:MonitorData}){
 const candidates=data.registryCandidates??[],unresolved=candidates.filter(r=>r.match_status!=='approved');
 return <>
 <section className={s.panel}><h2>Official product coverage</h2><p>The approved research registry is reconciled against enabled Solana security identities in Backpack’s official APIs. Positive supply is reported separately from product lifecycle.</p><p>Latest reconciliation observed {candidates.length||'no'} enabled identities; {unresolved.length} remain outside the approved universe or conflict with it.</p>{unresolved.length>0&&<details><summary>Review {unresolved.length} unresolved official identities</summary><div className={s.tableWrap}><table><thead><tr><th>Symbol</th><th>Mint</th><th>Status</th><th>Reason</th></tr></thead><tbody>{unresolved.map(r=><tr key={`${r.token_symbol}-${r.solana_mint}`}><td>{String(r.token_symbol)}</td><td><code>{String(r.solana_mint).slice(0,6)}…{String(r.solana_mint).slice(-6)}</code></td><td>{String(r.match_status)}</td><td>{String(r.detail)}</td></tr>)}</tbody></table></div></details>}</section>
 <section className={s.panel}><h2>Sourced market evidence and product events</h2><p>External reports are preserved as context and never substituted for internally complete totals.</p><div className={s.tableWrap}><table><thead><tr><th>Date</th><th>Evidence</th><th>Value</th><th>Coverage</th><th>Source / limitation</th></tr></thead><tbody>{(data.externalObservations??[]).map(r=><tr key={String(r.evidence_key)}><td>{String(r.published_at).slice(0,10)}</td><td>{String(r.metric).replaceAll('_',' ')}</td><td>{r.unit==='USD'?money(r.value):String(r.value??'N/A')} {r.observation_kind==='change'?`increase vs prior ${String(r.period_days)}D`:String(r.observation_kind)}</td><td>{String(r.coverage_status)}</td><td><details><summary><a href={String(r.source_url)} target="_blank" rel="noreferrer">{String(r.source_publisher)}</a></summary><p>{String(r.methodology)}</p><p>{String(r.limitation)}</p></details></td></tr>)}{!(data.externalObservations??[]).length&&<tr><td colSpan={5}>No approved external observations.</td></tr>}</tbody></table></div><h3>Product timeline</h3><div className={s.tableWrap}><table><thead><tr><th>Date</th><th>Event</th><th>Assets</th><th>Evidence</th></tr></thead><tbody>{(data.economyEvents??[]).map(r=><tr key={String(r.event_key)}><td>{String(r.event_at).slice(0,10)}</td><td><b>{String(r.title)}</b><br/><span>{String(r.description)}</span></td><td>{Array.isArray(r.asset_symbols)?r.asset_symbols.join(', '):String(r.asset_symbols)}</td><td><a href={String(r.source_url)} target="_blank" rel="noreferrer">{String(r.evidence_status)}</a><br/><small>{String(r.limitation)}</small></td></tr>)}</tbody></table></div></section>
 </>;
}
export function ResearchContext({data}:{data:MonitorData}){
 const states=data.environment??[];
 const stale=!!data.asOf&&Date.now()-Date.parse(`${data.asOf}T00:00:00Z`)>48*3600000;
 return <>
 <section className={s.panel}><h2>Adoption / trading environment</h2><p>Observable conditions, not an investment score. Classification requires complete trading volume, stable asset coverage and two adjacent windows.</p>
 <div className={s.tableWrap}><table><thead><tr><th>Window</th><th>State</th><th>Net issuance / starting AUM</th><th>AUM growth</th><th>Holder growth</th><th>Trading growth</th><th>Evidence</th></tr></thead><tbody>{[7,30].map(period=>{const r=states.find(r=>Number(r.period_days)===period);return <tr key={period}><td>{period}D</td><td>{stale?'Stale':String(r?.state??'Unavailable')}</td><td>{pct(r?.issuance_aum_pct)}</td><td>{pct(r?.aum_growth_pct)}</td><td>{pct(r?.holder_growth_pct)}</td><td>{pct(r?.trading_growth_pct)}</td><td><details><summary>Why · {data.asOf??'No capture'}</summary><p>{String(r?.reason??'No complete captured research window yet. Sampled swaps are insufficient.')}</p><p>Thresholds: issuance {pct(r?.issuance_threshold_pct)}; AUM/holders {pct(r?.growth_threshold_pct)}; trading {pct(r?.trading_threshold_pct)}.</p><p>{String(r?.methodology??'Missing values remain unavailable. No quadrant is inferred from BP price.')}</p></details></td></tr>;})}</tbody></table></div></section>
 <section className={s.panel}><h2>Issuer coverage</h2><p>Registry coverage only. Market share is unavailable until comparable, verified category observations exist. Asset holder counts cannot be summed into unique category investors.</p><div className={s.tableWrap}><table><thead><tr><th>Issuer</th><th>Approved assets</th><th>Latest stored observation</th><th>Category share</th></tr></thead><tbody>{(data.competitors??[]).map((r:Row)=><tr key={String(r.id)}><td>{String(r.name)}</td><td>{String(r.assets)}</td><td>{String(r.latest_capture??'Unavailable')}</td><td>N/A</td></tr>)}</tbody></table></div>{!data.competitors?.length&&<p>Coverage registry awaiting initialization.</p>}</section>
 <details className={s.panel}><summary>How to read this evidence</summary><p>Reference AUM is token supply × the underlying equity reference price. It can rise with equity prices; net on-chain issuance separates changes in supply. Issuance is not automatically a customer deposit.</p><p>Meaningful wallets exclude dust and sufficiently verified system accounts. A wallet is not necessarily one investor. Daily snapshots cover approved securities in this registry, not every security Backpack may issue.</p><p>Partial swap volume is an observed sample, not market-wide activity. Transfers are not trades. A stale equity reference can create an apparent premium without an executable arbitrage.</p><p>Verified describes a particular source check, not overall completeness. Estimated includes calculation assumptions; Partial means incomplete coverage; Stale identifies an old observation; Unavailable means the evidence cannot support a value. Expand each metric’s source and method for its timestamp and limitations.</p><div className={s.tableWrap}><table><thead><tr><th>Registered security</th><th>Approval</th><th>Primary evidence</th><th>Verified at</th></tr></thead><tbody>{data.assets.filter(a=>a.asset_type!=='bp').map(a=><tr key={String(a.id)}><td>{String(a.token_symbol)}</td><td>{String(a.verification_status)}</td><td>{String(a.official_source??'').startsWith('https://')?<a href={String(a.official_source)} target="_blank" rel="noreferrer">Registry source</a>:'Unavailable'}</td><td>{String(a.source_verified_at??'Unavailable')}</td></tr>)}</tbody></table></div></details>
 </>;
}
